trang dang ki tai khoan
<?php
$title = "Đăng kí tài khoản";
$this->headTitle($title);

?>

<h1><?php echo $title;?></h1>

<?php

$form = $this->form;
$form->setAttribute('action', $this->url('login', array('action' => 'register')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('username'));
echo $this->formRow($form->get('password'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>