<input type="hidden" id="hidden-pageID" value="<?php echo $pageID; ?>">
<input type="hidden" id="hidden-userIDNow" value="<?php
$masterID = $userNow;
        if($checkRole == "ADMIN" || $checkRole == "MOD"){
            $masterID = $pageID;
        }
echo $masterID;
?>">

<section class="lightbox">
    <div class="page-logo">
        <img src="<?php echo $this->basePath().'/uploads/'.$pageInfo['bindingImage']['imageLogo']?>">
    </div>
</section>

<section class="wrapper">

    <div class="admin-panel"></div>

    <div class="page-cover">
        <?php
        foreach($pageInfo['bindingImage']['imageSlideShow'] as $node)
        {
        ?>

            <div class="div-image">
                <img src="<?php echo $this->basePath().'/uploads/'.$node; ?>">
                <section class="bottom-blur"></section>
            </div>

        <?php
        }
        ?>

    </div>
    
    <div class="voidClass">
         <a href="<?php echo $this->basePath(); ?>">
             <img src="<?php echo $this->basePath(); ?>/img/zess_logo2.png">
         </a>
    </div>

    <style type="text/css">

    </style>

    <div class="albumMap" >
        <div class="infoPage" >

            <?php
            if($checkRole == 'ADMIN')
            {
            ?>

                <a class="config-infoPage" href="<?php echo $this->basePath().'/fanpage/editinfo?pageID='.$pageID; ?>"
                   style="left:0px; margin-top: -22px;"></a>
                <a class="config-infoPage" href="<?php ?>" style="right:0px; margin-top: -22px;"></a>

            <?php
            }
            ?>

            <div class="left-infoPage" >
                <div class="left-LogoPage">
                    <img src="<?php echo $this->basePath().'/uploads/' .$pageInfo['bindingImage']['imageAva']; ?>">
                </div>
                <div class="rightLogoPage" >
                    <div class="rightlogo-Like" >
                        <a id="buttonLikePage">Thích</a>
                    </div>
                    <div class="rightLogo-LikeSum">
                        <span class="countLikePage"> <?php echo $pageInfo['bindingInfo']['pageLike'];?>
                            <label> lượt thích</label>
                        </span>
                    </div>

                </div>
                <div class="namePage" >
                    <span class="nameOfPage" ><?php echo $pageInfo['bindingInfo']['pageName'] ?></span>
                </div>
            </div>
            <div class="right-infoPage">
                <?php echo $pageInfo['bindingInfo']['pageDes'] ?>
            </div>
        </div>

        <div class="mapToPage" id="mapToPageID" style="">

            <!-- SHOW GOOGLE MAP FOR PAGE     -->
        </div>

    </div>

        <!--  DIV SHOW ALBUM BY GOOGLE MAPS  -->
    <div class="page-intro">


        <script id="galleryTmpl" type="text/x-jquery-tmpl">
            <div class="mp-album-outer">
                <div class="mp-album">
                    {{each(i, option) tmplPhotosData}}
                    <a href="${tmplPhotosData[i]}"><img src="${tmplPhotosData[i]}"/></img></a>
                    {{/each}}
                </div>
            </div>
        </script>
        <script id="galleryAlbumTmpl" type="text/x-jquery-tmpl">
            <div id="mp-album-overlay" class="mp-album-overlay">
                <div class="mp-album-nav">
                    <span class="mp-album-nav-prev">Lùi</span>
                    <span class="mp-album-nav-next">Tiến</span>
                </div>
                <div class="mp-image-loading-small">Đang tải...</div>
                <div class="mp-album-image-wrapper">
                    <div class="mp-album-image">
                        <img src="${tmplPhotoData.source}"/>
                        <a href="#" class="mp-album-image-zoom">Hình thực tế</a>
                    </div>
                </div>
                <span class="mp-album-overlay-close">Đóng</span>
            </div>
        </script>
        <script id="galleryFullscreenTmpl" type="text/x-jquery-tmpl">
            <div id="mp-image-overlay" class="mp-image-overlay">
                <div class="mp-loading">Loading...</div>
                <img src="${tmplPhotoData.source}" style="display:none;"/>
                <div class="mp-image-overlay-desc">
                    <h2 class="mp-label">${tmplPhotoData.description}</h2>
                </div>
                <span class="mp-image-overlay-close">Đóng</span>
            </div>
        </script>

        <div class="mp-container" id="mp-container">
<!--            <a class="config-infoPage" href="#" style="right:-32px;"></a>-->
            <div class="mp-map-wrapper" id="map"></div>
            <div class="mp-album-wrapper" id="mp-album-wrapper"></div>
        </div>

    </div>

    <div class="page-content">
<!--        ACTIVITY PAGE POST ON WALL-->
        <style type="text/css">



        </style>
        <div class="page-activity">
            <div class="toolsPost" style="width: 100%; padding-left: 15px; padding-right: 15px;">
                <div class="titleTools" style="width: 100%;">
                    <ul>
                        <li id="pagepostStatus" class="setmenuClicked">Trạng thái</li>

                        <?php
                        if($checkRole == "ADMIN" || $checkRole == "MOD")
                        {
                        ?>
                            <li id="pagepostImage" class="menuNormal">Đăng ảnh</li>
                            <li id="pagepostVideo" class="menuNormal">Đăng Video</li>
                            <li id="pagepostPlace" class="menuNormal">Đăng Chia sẻ</li>
                        <?php
                        }
                        ?>

                    </ul>
                </div>

                <div id="firstBonnus" class="clickStatus boxPage" style="display: block;">
                    <div id="" class="divBottomActive" style="left:-11px;"></div>

                    <div style="display: block; width: 100%; float: left;">
                        <form method="post" id="form-pagePostStatus">
                            <textarea name="cnt_page_status" id="cnt_page_status" placeholder="Nhập trạng thái..." class="textStatus"></textarea>
                            <input class="btnPostStatus" id="btn_post_status" type="submit" value="Đăng">
                            <p id="error_post_status" style="color:red; display: block; text-align: center; padding-top: 15px; display: none">
                            </p>
                        </form>
                    </div>

                </div>

                <?php
                if($checkRole == "ADMIN" || $checkRole == "MOD")
                {
                ?>

                <div id="secoundBonnus" class="clickStatus boxPage" style="display: none;">
                    <div id="" class="divBottomActive" style=" left: 105px; width: 111px;"></div>
                    <div style="display: block; width: 100%; float: left; padding:2% 3% 0 3%; ">
                        <form method="post">
                            <div class="wrap-uploadImage" style="width: 17%;">
                                <input type="file" class="uploadImage" accept="image/*">
                                Chọn ảnh
                            </div>
                            <div style="width: 80%;">
                                <label>Nhập bình luận về ảnh</label>
                                <input type="text" class="btnTextImage" placeholder="...">
                                <input type="submit" class="btnPostStatus" value="Đăng" style="margin-right: 0px;">
                            </div>
                        </form>
                    </div>

                </div>

                <div id="lastBonnus" class="clickStatus boxPage" style="display: none;">
                    <div id="" class="divBottomActive" style="left: 217px; width: 124px;"></div>
                    <div style="display: block; width: 100%; float: left; padding:2% 3% 0 3%; ">
                        <form method="post">
                            <div class="wrap-uploadVideo" style="width: 17%;">
                                <input type="file" class="uploadVideo" accept="video/mp4">
                                Chọn video
                            </div>
                            <div style="width: 82%;">
                                <label>Nhập bình luận về video</label>
                                <input type="text" class="btnTextImage" placeholder="...">
                                <input type="submit" class="btnPostStatus" value="Đăng" style="margin-right: 0px;">
                            </div>
                        </form>
                    </div>

                </div>

                <div id="sharePlaceBonnus" class="clickStatus boxPage" style="display: none;">
                    <div id="" class="divBottomActive" style="left: 342px;width: 132px;"></div>
                    <div style="display: block; width: 100%; float: left; padding:2% 3% 0 3%; ">
                        <form method="post">
                            <div class="wrap-uploadPlace" style="width: 17%;">
                                <input type="file" class="uploadImage" accept="image/*">
                                Chọn ảnh
                            </div>
                            <div style="width: 80%;">
                                <label>Nhập bình luận về ảnh</label>
                                <input type="text" class="btnTextImage" placeholder="...">
                                <textarea class="textStatus" placeholder="Nhập chia sẻ về địa điểm..."
                                          style="width: 100%; margin-top: 15px; margin-left: 0px; margin-right: 0px;"></textarea>
                                <input type="submit" class="btnPostStatus" value="Đăng" style="margin-right: 0px;">
                            </div>
                        </form>
                    </div>

                </div>

                <?php } ?>

            </div>
            <div style="width: 100%; height: 15px;"></div>
            <div class="pagePost">

                <div class="container">

                    <div class="main">

                        <ul class="cbp_tmtimeline">

                            <?php

//                            var_dump($binding);die();



                            if(isset($binding))
                            {
                                arsort($binding);
                                foreach($binding as $node)
                                {
                            ?>
                                    <li>
                                        <time class="cbp_tmtime" datetime="

                                        <?php

                                        $timestamp = $node['createdtime'];
                                        echo date('Y-m-d h:s', $timestamp);
                                        ?>
                                        ">
                                            <span><?php echo date('d/m/Y', $timestamp) ?></span>
                                            <span><?php echo date('H:i', $timestamp) ?></span>
                                        </time>
                                        <div class="cbp_tmicon cbp_tmicon-earth"></div>
                                        <div class="cbp_tmlabel">
                                            <h2>
                                                <?php
                                                echo $pageInfo['bindingInfo']['pageName'];
                                                $typeAction = $node['content']['type'];
                                                if($typeAction == 'addStatus')
                                                {
                                                    echo " - cập nhật trạng thái";
                                                }
                                                elseif($typeAction=="changeAva")
                                                {
                                                    echo ' -  cập nhật ảnh đại diện';
                                                }
                                                elseif($typeAction=="changeLogo")
                                                {
                                                    echo ' -  cập nhật ảnh logo';
                                                }
                                                elseif($typeAction=="changeSlide")
                                                {
                                                    echo ' -  cập nhật slideshow ảnh nền';
                                                }
                                                elseif($typeAction=="addImage")
                                                {
                                                    echo ' -  thêm một ảnh mới';
                                                }

                                                ?>
                                            </h2>
                                            <p>
                                                <?php
                                                if($typeAction == 'addStatus')
                                                {
                                                    echo $node['content']['source'];
                                                }
                                                elseif($typeAction == 'addImage' or $typeAction == 'changeSlide' or $typeAction=='changeLogo' or $typeAction=='changeAva')
                                                {
                                                    echo $node['content']['descript'];
                                                    echo '<img src="'.$this->basePath().'/uploads/'.$node['content']['source'].'">';
                                                }
                                                ?>
                                            </p>
                                            <a id="<?php echo $node['actionid']; ?>" class="showInstanceCMT">Xem thêm bình luận</a>
                                        </div>

                                    </li>

                            <?php
                                }
                            }
                            ?>

                            <li>
                                <time class="cbp_tmtime" datetime=""><span></span> <span></span></time>
                                <div class="cbp_tmicon cbp_tmicon-screen"></div>
                                <div class="cbp_tmlabel">
                                    <h2><?php echo $pageInfo['bindingInfo']['pageName'] ?></h2>
                                    <p>Được thành lập vào ngày
                                    <?php
                                    $dt = new DateTime();
                                    $dt->setTimestamp(substr($pageInfo['bindingInfo']['pageID'], 4));
                                    echo date_format($dt, 'd-m-Y');
                                    ?>
                                    <br>
                                        Đã gia nhập trang mạng fanpage của mạng xã hội du lịch và ẩm thực Zess.

                                    </p>
                                </div>
                            </li>
                        </ul>

                    </div>

                    <div class="absolute-comment" style="display: none;">
                        <div class="arrow_box">
                            <div class="close-arrowbox">Đóng</div>
                            <div class="toolComment" style="padding-top: 10px; padding-bottom: 10px;">
                                <ul>
                                    <li class="toolComment-Like">Thích(0)</li>
                                    <li class="toolComment-cmt">Bình luận(0)</li>
                                    <li class="toolComment-share">Chia sẻ(0)</li>
                                </ul>
                            </div>

                            <div class="content-toolComment" id="notdelete" style="padding-bottom: 5px;">
                                <div class="avatar-memberComment" style="float: left;">
                                    <img id="<?php echo 'img_'.$masterID; ?>"
                                        name="<?php
                                    if(isset($avaWho['name'])) {
                                        echo $avaWho['name'];
                                    } else{
                                        echo  $pageInfo['bindingInfo']['pageName'];
                                    }  ?>"
                                         src="<?php
                                         if($checkRole == 'ADMIN' or $checkRole == 'MOD')
                                         {
                                             echo $this->basePath().'/uploads/' .$pageInfo['bindingImage']['imageAva'];
                                         }
                                         else{
                                             echo $this->basePath().'/uploads/'.$avaWho['pathAva'];
                                          }

                                         ?>" style="height: 100%; width: 100%;">
                                </div>
                                <div class="info-memberComment" style="float: left;width: 85%;padding-top: 5px;">
                                    <form method="post">
                                        <textarea class="commitComment" placeholder="nhập bình luận của bạn..."></textarea>
                                        <input class="btnCommitComment" type="submit" value="Đăng">
                                    </form>
                                </div>
                            </div>

                        </div>

                    </div>


                </div>

            </div>

        </div>



<!--       ACTIVITY OF MEMBER POST ON WALL -->
        <div class="page-member-activity">

            <div class="title-memberPost">
                <span>Bài đăng của những người khác lên Nhà hàng sao việt</span>
            </div>

            <?php

            function time_difference($date)
            {
                if(empty($date)) {
                    return "unidentifed";
                }
                $periods = array("giây", "phút", "giờ", "ngày", "tuần", "tháng", "năm", "thập kỷ");
                $lengths = array("60","60","24","7","4.35","12","10");
                $now = time();
                $unix_date = $date;
                if(empty($unix_date)) {
                    return "Bad date";
                }
                if($now > $unix_date) {
                    $difference = $now - $unix_date;
                    $tense = "trước"; } else {
                    $difference = $unix_date - $now;
                    $tense = "vừa mới";
                }
                for($j = 0; $difference >= $lengths[$j] && $j < count($lengths)-1; $j++) {
                    $difference /= $lengths[$j];
                }

                $difference = round($difference);

                if($difference != 1) {
                    $periods[$j].= " ";
                }
                return "$difference $periods[$j] {$tense}";
            }

            function getFullTime($date)
            {
                $value  = ' lúc '.date('H', $date). ' giờ ';
                $value .= date('i', $date) . ' phút';
                $value .= ' ngày '.date('d/m/Y', $date);
                return $value;
            }

            if(isset($userPost))
            {
                foreach($userPost as $node)
                {
            ?>

                    <div class="memberPost">
                        <div class="content-memberPost">
                            <div class="imageMember">
                                <img src="<?php echo $this->basePath().'/uploads/'. $node['pathava']; ?>">
                            </div>
                            <div class="infoMember">
                                <span class="nameMember">
                                    <a href="<?php echo $this->basePath().'/success?user='.$node['actionuser']; ?>">
                                        <?php echo $node['username']; ?>
                                    </a>
                                </span>
                                <span class="statusMember"><?php echo $node['statuscontent']; ?></span>
                        <span class="timepostMember">
                            <a href="#" title="<?php echo getFullTime($node['createdtime']); ?>">
                                <?php echo time_difference($node['createdtime']); ?>
                            </a>
                        </span>
                            </div>
                        </div>
                    </div>

            <?php
                }
            }
            else
            {
                echo 'Hiện tại chưa có bài viết nào!';
            }
            ?>





        </div>
    </div>

    <div style="height: 300px; width: 100%; float: left;"></div>

</section>

<footer>

</footer>

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/jquery.tmpl.min.js"></script>
<!--<script src="http://maps.google.com/maps/api/js?sensor=true" type="text/javascript"></script>-->
<script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyAYVsGMEN8T8D9-TtSVgQQgM3ecNbYYFMw&sensor=false" type="text/javascript"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/jquery.mousewheel.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/jquery.jscrollpane.min.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/mapalbum.js"></script>


<script type="text/javascript">
    var windowHeight = jQuery(window).height();
    var windowWidth  = jQuery(window).width();



    jQuery(document).ready(function() {
        jQuery('.lightbox').slideUp(1500);

        jQuery('.page-cover > div:gt(0)').hide();
        setInterval(function() {
            jQuery('.page-cover > div:first')
                .fadeOut(1000)
                .next()
                .fadeIn(1000)
                .end()
                .appendTo('.page-cover');
        },  3000);
    });

</script>

<script>

    function addInfoWindowHandle()
    {
        var divContent = document.createElement('div');
        divContent.id = "content";
        var divSiteNotice = document.createElement('div');
        divSiteNotice.id = "siteNotice";
        var tagH1 = document.createElement('h1');
        tagH1.id = "firstHeading";
        tagH1.className = "firstHeading";
        tagH1.textContent = "<?php echo $pageInfo['bindingInfo']['pageName'] ?>";
        var divBodyContent = document.createElement('div');
        divBodyContent.id = "bodyContent";
        var tagPre = document.createElement('p');
        jQuery(tagPre).text("<?php echo str_replace(array("\r\n","\r","\n"),' ',$pageInfo['bindingInfo']['pageMapInfo']); ?>");

        divContent.appendChild(divSiteNotice);
        divContent.appendChild(tagH1);
        divContent.appendChild(divBodyContent);
        divBodyContent.appendChild(tagPre);

        return divContent;
    }

    function initialize()
    {
        var pageLongt = <?php
        if(isset($pageInfo['bindingInfo']['pageLongt']))
            echo $pageInfo['bindingInfo']['pageLongt'];
         else
            echo 106.68617248535156;
        ?>;
        var pageLat = <?php
        if(isset($pageInfo['bindingInfo']['pageLat']))
            echo $pageInfo['bindingInfo']['pageLat'];
        else
            echo 10.779348472547026;
        ?>;
        var myLatlng = new google.maps.LatLng(pageLat,pageLongt);
        var mapProp = {
            center:myLatlng,
            zoom:15,
            scrollwheel: false,
            mapTypeId:google.maps.MapTypeId.ROADMAP
        };
        var map=new google.maps.Map(document.getElementById("mapToPageID")
            ,mapProp);

        var newImage = '<?php echo $this->basePath().'/img/icon-office-building.png' ?>';

        var marker = new google.maps.Marker({
            position: myLatlng,
            map: map,
            icon : newImage,
            title: "Nhấn để xem thông tin chi tiết!"
        });
        marker.setAnimation(google.maps.Animation.BOUNCE);



        var contentString = addInfoWindowHandle();
        var infoWindow = new google.maps.InfoWindow({
            content: contentString,
            maxWidth: 400
        });

        google.maps.event.addListener(marker, 'click', function() {
            infoWindow.open(map,marker);
        });

    }


    google.maps.event.addDomListener(window, 'load', initialize);
</script>

<script type="text/javascript">

    jQuery(document).ready(function(){

        function vainoiFunction(idofDivComment)
        {
            var e = document.getElementById(idofDivComment);
            var offset = {x:0,y:0};
            while (e)
            {
                offset.x += e.offsetLeft;
                offset.y += e.offsetTop;
                e = e.offsetParent;
            }

            if (document.documentElement && (document.documentElement.scrollTop || document.documentElement.scrollLeft))
            {
                offset.x -= document.documentElement.scrollLeft;
                offset.y -= document.documentElement.scrollTop;
            }
            else if (document.body && (document.body.scrollTop || document.body.scrollLeft))
            {
                offset.x -= document.body.scrollLeft;
                offset.y -= document.body.scrollTop;
            }
            else if (window.pageXOffset || window.pageYOffset)
            {
                offset.x -= window.pageXOffset;
                offset.y -= window.pageYOffset;
            }

//                    alert(offset.x + '\n' + offset.y);
            return offset.y;
        }

        jQuery('.titleTools>ul>li').each(function(){

            jQuery(this).click(function(){
                jQuery('.titleTools>ul>li').removeClass('menuNormal setmenuClicked').addClass('menuNormal');
                jQuery('.clickStatus').hide();
                jQuery(this).removeClass('menuNormal').addClass('setmenuClicked');

                var index = jQuery(this).index();
                if(index == 0){
                    jQuery('#firstBonnus').show();
                }
                else{
                    if(index == 1){
                        jQuery('#secoundBonnus').show();
                    }
                    else{
                        if(index == 2){
                            jQuery('#lastBonnus').show();
                        }else{
                            jQuery('#sharePlaceBonnus').show();
                        }
                    }
                }

            });
        });

        clickShowComment();

        function loadCommentbyActID(actionID)
        {
            var dataval = "actionID="+actionID;
//            alert(dataval);
            jQuery.ajax({
                type: "POST",
                url: "<?php echo $this->url('fanpage', array('action' => 'loadcommentbyid')); ?>",
                data: dataval,
                async:false,
                success: function(data) {
//                    alert(data);return;
                    data = jQuery.parseJSON(data);
                    deleteOldComment();
                    if(data['success'] == 1)
                    {
                        var divAbsolute = jQuery('.absolute-comment');
                        var i = 0;
                        var maxi = data['commentData'].length;
                        function loopShowCMT()
                        {
                            if(i >= maxi)
                            {
                                return;
                            }
                            var linkAnh = '<?php echo $this->basePath().'/uploads/'; ?>' + data['commentData'][i]['avauser'];
                            var cmtContent = data['commentData'][i]['commentcontent'];
                            var nameUserPost = data['commentData'][i]['nameuser'];
                            instancePostComment(cmtContent, linkAnh, nameUserPost, data['commentData'][i]['createdtime'], 'none');
                            i++;
                            setTimeout(loopShowCMT, 400);
                        }
                        loopShowCMT();
                    }
                },
                error: function() {
                    alert("Hệ thống đang bảo trì, xin hãy thử lại sau một ít phút nữa!");
                }
            });
        }


        function clickShowComment()
        {
            //instance show comment
            jQuery('.close-arrowbox').click(function(){
                var divShow = jQuery('.absolute-comment');
                var heightNow = divShow.css('height');
                var widthNow = divShow.css('width');
                divShow.animate({
                    opacity:0,
                    marginTop: '-30px'
                }, 1000, function(){
                    jQuery(this).css({'display': 'none', 'opacity': 1, 'marginTop':0});
                });
            });

            jQuery('.showInstanceCMT').each(function(){
                jQuery(this).click(function(){
                    var heightParent = jQuery(this).parent().height();
                    var idforShowCMT = jQuery(this).attr('id');
                    var posTop = vainoiFunction(idforShowCMT) - heightParent;
                    var commentInstance = jQuery('.absolute-comment');
                    var isDisplayorNor = commentInstance.css('display');

                    //gan id cho div comment
                    commentInstance.attr('id', idforShowCMT);

                    //load data comments
                    if(isDisplayorNor == "none")
                    {
                        commentInstance.css('top', posTop);
                    }
                    if(heightParent < 215)
                    {
                        heightParent = 215;
                    }

                    commentInstance.fadeIn(1000);
                    commentInstance.animate({
                        top: posTop,
                        height: heightParent
                    }, 1200, function(){
                        loadCommentbyActID(idforShowCMT);
                    });

                    var pageID = jQuery('#hidden-pageID').val();
//                    var userNow = jQuery('#hidden-userIDNow').val();
                });
            });

            jQuery('.btnCommitComment').click(function(){
                var time = getTimestampNow();
                var actionID = jQuery('.absolute-comment').attr('id');
                var contentComt = jQuery('.commitComment');
                var valueComt = contentComt.val();
                var actionLocation = jQuery('#hidden-pageID').val();
                var actionUser = jQuery('#hidden-userIDNow').val();
                if(valueComt.length == 0)
                {
                    alert('Bạn chưa nhập nội dung bình luận của mình!');
                    contentComt.focus();
                }
                else
                {
                    insertNewComment(actionID, actionUser, actionLocation, valueComt, time);
                }

                return false;
            });
        }

        function insertNewComment(actionID, actionUser, actionLocation, cmtContent, createdTime)
        {
            var dataval = "actionID="+actionID+"&actionUser="+actionUser+"&actionLocation="+actionLocation+"&cmtContent="+cmtContent+"&createdTime="+createdTime;

            jQuery.ajax({
                type: "POST",
                url: "<?php echo $this->url('fanpage', array('action' => 'insertnewcomment')); ?>",
                data: dataval,
                async:false,
                success: function(data) {
                    data = jQuery.parseJSON(data);
                    if(data['success'] == 1)
                    {
                        var linkAnh = '<?php
                        echo $this->basePath().'/uploads/';
                        if(isset($avaWho['pathAva']))
                            echo $avaWho['pathAva'];
                        else
                            echo $pageInfo['bindingImage']['imageAva'];
                        ?>';
                        var nameUserPost = jQuery('#img_'+actionUser).attr('name');
                        instancePostComment(cmtContent, linkAnh, nameUserPost, createdTime, 'instance');
                    }
                },
                error: function() {
                    alert("Hệ thống đang bảo trì, xin hãy thử lại sau một ít phút nữa!");
                }
            });
        }

        function instancePostComment(cmtContent, linkAvatar, nameUserPost, createdTime ,typeComment)
        {
            var newDate = new Date(createdTime*1000);
            var timeConvert = ' lúc ' + newDate.getHours()+':'+newDate.getMinutes();
            var dateConvert = ' ngày ' + newDate.getDate()+'/'+(newDate.getMonth()+1)+'/'+newDate.getFullYear();
            var timePost ="";
            if(typeComment == 'instance')
            {
                timePost = " vài giây trước"
            }
            else
            {
                timePost = timeConvert + dateConvert;
            }

            var divToolComment = document.createElement('div');
            divToolComment.className = "content-toolComment";

            var divAvatar = document.createElement('div');
            divAvatar.className = "avatar-memberComment";

            var imgAvatar = document.createElement('img');
            jQuery(imgAvatar).attr('src', linkAvatar);

            var divInfoMem = document.createElement('div');
            divInfoMem.className = 'info-memberComment';

            var tagANameMem = document.createElement('a');
            tagANameMem.className = "name-membercmt";

            var tagSpanofName = document.createElement('span');
            tagSpanofName.textContent = nameUserPost;

            var tagAcontentCmt = document.createElement('a');
            tagAcontentCmt.className = "countlike-membercmt";

            var tagASpanofContent = document.createElement('span');
            tagASpanofContent.textContent = cmtContent;

            var tagSpanofLikeButton = document.createElement('span');
            tagSpanofLikeButton.className = "like-time-membercmt";

            var tagAofSpanofLikeButton = document.createElement('a');
            tagAofSpanofLikeButton.textContent = "Thích(0)";

            divToolComment.appendChild(divAvatar);
                divAvatar.appendChild(imgAvatar);
            divToolComment.appendChild(divInfoMem);
                divInfoMem.appendChild(tagANameMem);
                    tagANameMem.appendChild(tagSpanofName);
                divInfoMem.appendChild(tagAcontentCmt);
                    tagAcontentCmt.appendChild(tagASpanofContent);
                divInfoMem.appendChild(tagSpanofLikeButton);
                    tagSpanofLikeButton.appendChild(tagAofSpanofLikeButton);
                    jQuery(tagSpanofLikeButton).append(timePost);

            jQuery(divToolComment).css('opacity', 0);
            jQuery('.toolComment').after(divToolComment);
//            jQuery(divToolComment).slideDown(400);
            jQuery(divToolComment).animate({
                opacity:1
            },600);
            jQuery('.absolute-comment').css('height', 'auto');
        }


        function deleteOldComment()
        {
            jQuery('.content-toolComment').each(function(){
                var checkDel = jQuery(this).attr('id');
                if(checkDel != 'notdelete')
                {
                    jQuery(this).hide(600);
                    jQuery(this).remove();
                }
            });
        }

        //////////////////////////START POST STATUS OF PAGE////////////////////////////
        function getTimestampNow()
        {
            var datenow = new Date();
            datenow = parseInt(datenow.setFullYear(datenow.getFullYear(), datenow.getMonth(), datenow.getDate())/1000);
            return datenow;
        }

        function instancePost(createTime, headTitle, content)
        {
            var newDate = new Date(createTime*1000);
            var timeConvert = newDate.getHours()+':'+newDate.getMinutes();
            var dateConvert = newDate.getDate()+'/'+(newDate.getMonth()+1)+'/'+newDate.getFullYear();
//            alert(timeConvert + '  ' + dateConvert );

            var tagLi = document.createElement('li');

            var tagTime = document.createElement('time');
            tagTime.className = "cbp_tmtime";
            tagTime.dateTime = dateConvert + ' ' + timeConvert;

            var tagSpan1 = document.createElement('span');
            tagSpan1.textContent = dateConvert;

            var tagSpan2 = document.createElement('span');
            tagSpan2.textContent = timeConvert;

            var divIcon = document.createElement('div');
            divIcon.className = "cbp_tmicon cbp_tmicon-earth";

            var divContent = document.createElement('div');
            divContent.className = "cbp_tmlabel";

            var tagH2 = document.createElement('h2');
            tagH2.textContent = headTitle;

            var tagP = document.createElement('p');
            tagP.textContent = content;

            var tagaShowComment = document.createElement('a');
            tagaShowComment.className = "showInstanceCMT";
            tagaShowComment.id = "ACT" + createTime;
            tagaShowComment.textContent = "Xem thêm bình luận";

            tagLi.appendChild(tagTime);
                tagTime.appendChild(tagSpan1);
                tagTime.appendChild(tagSpan2);
            tagLi.appendChild(divIcon);
            tagLi.appendChild(divContent);
                divContent.appendChild(tagH2);
                divContent.appendChild(tagP);
                divContent.appendChild(tagaShowComment);

            jQuery(tagLi).css({'margin-top':'-123px', 'margin-bottom': '123px', 'opacity': 0, 'position': 'relative'});
            jQuery('ul.cbp_tmtimeline').prepend(tagLi);
            jQuery(tagLi).animate({
                marginTop: '0px',
                marginBottom: '0px',
                opacity: 1
            }, 2000);

            clickShowComment();

        }

        function userPostStatus(content, userID, imagePath, username)
        {
            var divmemberPost = document.createElement('div');
            divmemberPost.className = "memberPost";

            var divContentPost = document.createElement('div');
            divContentPost.className = "content-memberPost";

            var divimageMember = document.createElement('div');
            divimageMember.className = "imageMember";

            var imgImageMember = document.createElement('img');
            jQuery(imgImageMember).attr('src', imagePath);

            var divInfoMember = document.createElement('div');
            divInfoMember.className = "infoMember";

            var spanNameMember = document.createElement('span');
            spanNameMember.className = "nameMember";

            var tagALinkMember = document.createElement('a');
            jQuery(tagALinkMember).attr('href', '<?php echo $this->basePath().'/success?user=';?>' + userID);
            tagALinkMember.textContent = username;

            var spanStatusMember = document.createElement('span');
            spanStatusMember.className = "statusMember";
            spanStatusMember.textContent = content;

            var spanTimepostMember = document.createElement('span');
            spanTimepostMember.className = "timepostMember";

            var tagATimepostMember = document.createElement('a');
            jQuery(tagATimepostMember).attr('href', '#');
            tagATimepostMember.title = " vài giây trước";
            tagATimepostMember.textContent = " vài giây trước";

            divmemberPost.appendChild(divContentPost);
                divContentPost.appendChild(divimageMember);
                    divimageMember.appendChild(imgImageMember);
                divContentPost.appendChild(divInfoMember);
                    divInfoMember.appendChild(spanNameMember);
                        spanNameMember.appendChild(tagALinkMember);
                    divInfoMember.appendChild(spanStatusMember);
                    divInfoMember.appendChild(spanTimepostMember);
                        spanTimepostMember.appendChild(tagATimepostMember);
            jQuery(divContentPost).css('opacity', 0);
            jQuery('.title-memberPost').after(divmemberPost);
            jQuery(divContentPost).animate({
                opacity: 1
            }, 1000);
        }

        jQuery('#btn_post_status').click(function(){
            //error_post_status
            var content_status = jQuery('#cnt_page_status').val();
            var userNow = jQuery('#hidden-userIDNow').val();
            var pageID = jQuery('#hidden-pageID').val();
            var createdTime = getTimestampNow();
                if(content_status.length == 0 || content_status.length < 6)
                {
                    jQuery('#error_post_status').text('Nội dung trạng thái không được bỏ trống hoặc phải có ít nhất 6 kí tự!').show(600).delay(4000).hide(400);
                }
                else
                {
                    var dataval = "userNow="+userNow+"&pageID="+pageID+"&statusContent="+content_status+"&createdTime="+createdTime;
//                    alert(dataval);

                    jQuery.ajax({
                        type: "POST",
                        url: "<?php echo $this->url('fanpage', array('action' => 'insertpagestatus')); ?>",
                        data: dataval,
                        async:false,
                        success: function(data) {
                            data = jQuery.parseJSON(data);
                            if(data['success'] == 1)
                            {
                                if(pageID == userNow)
                                {
                                    instancePost(createdTime, 'Nhà hàng việt nam', content_status);
                                }
                                else
                                {

                                    var linkImg =  "<?php echo $this->basePath().'/uploads/';
                                    if(isset($avaWho['pathAva'])) echo $avaWho['pathAva']; ?>";
                                    var nameUserPost = jQuery('#img_'+userNow).attr('name');
                                    userPostStatus(content_status, userNow, linkImg, nameUserPost);
                                }

                                jQuery('#form-pagePostStatus')[0].reset();
                            }
                        },
                        error: function() {
                            alert("Hệ thống đang bảo trì, xin hãy thử lại sau một ít phút nữa!");
                        }
                    });


                }
            return false;
        });
        //////////////////////////END POST STATUS OF PAGE////////////////////////////

    });
</script>