<input type="hidden" id="hidden-pageID" value="<?php echo $pageID; ?>">
<input type="hidden" id="hidden-userIDNow" value="<?php
$masterID = $userNow;
        if($checkRole == "ADMIN" || $checkRole == "MOD"){
            $masterID = $pageID;
        }
echo $masterID;
?>">

<section class="lightbox" id="logo_change">
    <div class="page-logo">
        <img src="<?php echo $this->basePath().'/uploads/'.$pageInfo['bindingImage']['imageLogo']?>">
    </div>
</section>

<section class="wrapper">

    <div class="admin-panel"></div>

    <div class="page-cover">
        <?php
        foreach($pageInfo['bindingImage']['imageSlideShow'] as $node)
        {
        ?>

            <div class="div-image">
                <img src="<?php echo $this->basePath().'/uploads/'.$node; ?>">
                <section class="bottom-blur"></section>
            </div>

        <?php
        }
        ?>

    </div>
    
    <div class="voidClass">
         <a title="Quay về trang cá nhân" href="<?php echo $this->basePath(); ?>">
             <img src="<?php echo $this->basePath(); ?>/img/zess_logo2.png">
         </a>
    </div>

    <style type="text/css">

    </style>

    <div class="albumMap" >
        <div class="infoPage" >

            <?php
            if($checkRole == 'ADMIN')
            {
            ?>

                <a class="config-infoPage" title="Vào chỉnh sửa trang fanpage" href="<?php echo $this->basePath().'/fanpage/editinfo?pageID='.$pageID; ?>"
                   style="left:0px; margin-top: -22px;"></a>
            <?php
            }
            ?>

            <div class="left-infoPage" >
                <div class="left-LogoPage">
                    <img src="<?php echo $this->basePath().'/uploads/' .$pageInfo['bindingImage']['imageAva']; ?>">
                </div>
                <div class="rightLogoPage" >
                    <div class="rightlogo-Like" >
                        <?php if($checkRole == "ADMIN" or $checkRole == "MOD"){}
                        else
                        {
                            if($checkLiked)
                                echo '<a id="buttonLikePage" class="unlike">Bỏ thích</a>';
                            else
                                echo '<a id="buttonLikePage" class="like">Thích</a>';
                        }
                        ?>
                    </div>
                    <div class="rightLogo-LikeSum">
                        <span class="countLikePage">
                            <p style="display: inline-block;" id="numberLike"><?php echo $pageInfo['bindingInfo']['pageLike'];?></p>
                            <label> lượt thích</label>
                        </span>
                    </div>

                </div>
                <div class="namePage" >
                    <span class="nameOfPage" ><?php echo $pageInfo['bindingInfo']['pageName'] ?></span>
                </div>
            </div>
            <div class="right-infoPage">
                <?php echo $pageInfo['bindingInfo']['pageDes'] ?>
            </div>
        </div>

        <div class="mapToPage" id="mapToPageID" style="">

            <!-- SHOW GOOGLE MAP FOR PAGE     -->
        </div>

    </div>

        <!--  DIV SHOW ALBUM BY GOOGLE MAPS  -->
    <div class="page-intro">


        <script id="galleryTmpl" type="text/x-jquery-tmpl">
            <div class="mp-album-outer">
                <div class="mp-album">
                    {{each(i, option) tmplPhotosData}}
                    <a href="${tmplPhotosData[i]}"><img src="${tmplPhotosData[i]}"/></img></a>
                    {{/each}}
                </div>
            </div>
        </script>
        <script id="galleryAlbumTmpl" type="text/x-jquery-tmpl">
            <div id="mp-album-overlay" class="mp-album-overlay">
                <div class="mp-album-nav">
                    <span class="mp-album-nav-prev">Lùi</span>
                    <span class="mp-album-nav-next">Tiến</span>
                </div>
                <div class="mp-image-loading-small">Đang tải...</div>
                <div class="mp-album-image-wrapper">
                    <div class="mp-album-image">
                        <img src="${tmplPhotoData.source}"/>
                        <a href="#" class="mp-album-image-zoom">Hình thực tế</a>
                    </div>
                </div>
                <span class="mp-album-overlay-close">Đóng</span>
            </div>
        </script>
        <script id="galleryFullscreenTmpl" type="text/x-jquery-tmpl">
            <div id="mp-image-overlay" class="mp-image-overlay">
                <div class="mp-loading">Loading...</div>
                <img src="${tmplPhotoData.source}" style="display:none;"/>
                <div class="mp-image-overlay-desc">
                    <h2 class="mp-label">${tmplPhotoData.description}</h2>
                </div>
                <span class="mp-image-overlay-close">Đóng</span>
            </div>
        </script>

        <div class="mp-container" id="mp-container">
<!--            <a class="config-infoPage" href="#" style="right:-32px;"></a>-->
            <div class="mp-map-wrapper" id="map"></div>
            <div class="mp-album-wrapper" id="mp-album-wrapper"></div>
        </div>

    </div>

    <div class="page-content">
<!--        ACTIVITY PAGE POST ON WALL-->
        <style type="text/css">



        </style>
        <div class="page-activity">
            <div class="toolsPost" style="width: 100%; padding-left: 15px; padding-right: 15px;">
                <div class="titleTools" style="width: 100%;">
                    <ul>
                        <li id="pagepostStatus" class="setmenuClicked">Trạng thái</li>

                        <?php
                        if($checkRole == "ADMIN" || $checkRole == "MOD")
                        {
                        ?>
                            <li id="pagepostImage" class="menuNormal">Đăng ảnh</li>
                            <li id="pagepostVideo" class="menuNormal">Đăng Video</li>
                            <li id="pagepostPlace" class="menuNormal">Đăng Chia sẻ</li>
                        <?php
                        }
                        ?>

                    </ul>
                </div>

                <div id="firstBonnus" class="clickStatus boxPage" style="display: block;">
                    <div id="" class="divBottomActive" style="left:-11px;"></div>

                    <div style="display: block; width: 100%; float: left;">
                        <form method="post" id="form-pagePostStatus">
                            <textarea name="cnt_page_status" id="cnt_page_status" placeholder="Nhập trạng thái..." class="textStatus"></textarea>
                            <input class="btnPostStatus" id="btn_post_status" type="submit" value="Đăng">
                            <p id="error_post_status" style="color:red; display: block; text-align: center; padding-top: 15px; display: none">
                            </p>
                        </form>
                    </div>

                </div>

                <?php
                if($checkRole == "ADMIN" || $checkRole == "MOD")
                {
                ?>

                <div id="secoundBonnus" class="clickStatus boxPage" style="display: none;">
                    <div id="" class="divBottomActive" style=" left: 105px; width: 111px;"></div>
                    <div style="display: block; width: 100%; float: left; padding:2% 3% 0 3%; ">
                        <form method="post" enctype="multipart/form-data"  id="form_upload_imagePage">
                            <div class="wrap-uploadImage" style="width: 17%;">
                                    <input type="file" id="btn_uploadImage_page" name="image" class="uploadImage" accept="image/*">
                                Chọn ảnh
                            </div>
                            <div style="width: 80%;">
                                <label>Nhập bình luận về ảnh</label>
                                <input type="text" class="btnTextImage" id="descript_imagePage" placeholder="...">
                                    <input type="submit" class="btnPostStatus" id="post_image_page" value="Đăng" style="margin-right: 0px;">
                            </div>
                        </form>
                    </div>

                </div>

                <div id="lastBonnus" class="clickStatus boxPage" style="display: none;">
                    <div id="" class="divBottomActive" style="left: 217px; width: 124px;"></div>
                    <div style="display: block; width: 100%; float: left; padding:2% 3% 0 3%; ">
                        <form method="post" enctype="multipart/form-data" id="form_upload_video">
                            <div class="wrap-uploadVideo" style="width: 17%;">
                                <input type="file" class="uploadVideo" name="video" id="btn_upload_video" accept="video/mp4">
                                Chọn video
                            </div>
                            <div style="width: 82%;">
                                <label>Nhập bình luận về video</label>
                                <input type="text" id="descript_upload_video" class="btnTextImage" placeholder="...">
                                <input type="submit" id="post_upload_video" class="btnPostStatus" value="Đăng" style="margin-right: 0px;">
                            </div>
                        </form>
                    </div>

                </div>

                <div id="sharePlaceBonnus" class="clickStatus boxPage" style="display: none;">
                    <div id="" class="divBottomActive" style="left: 342px;width: 132px;"></div>
                    <div style="display: block; width: 100%; float: left; padding:2% 3% 0 3%; ">
                        <form method="post" enctype="multipart/form-data" id="form_post_share">
                            <div class="wrap-uploadPlace" style="width: 17%;">
                                <input type="file" id="btn_post_share" name="image" class="uploadImage" accept="image/*">
                                Chọn ảnh
                            </div>
                            <div style="width: 80%;">
                                <label>Nhập bình luận về ảnh</label>
                                <input type="text" id="hashtag_share" class="btnTextImage" placeholder="...">
                                <textarea class="textStatus" id="descript_share" placeholder="Nhập chia sẻ về địa điểm..."
                                          style="width: 100%; margin-top: 15px; margin-left: 0px; margin-right: 0px;"></textarea>
                                <input type="submit" class="btnPostStatus" id="post_share_button" value="Đăng" style="margin-right: 0px;">
                            </div>
                        </form>
                    </div>

                </div>

                <?php } ?>

            </div>
            <div style="width: 100%; height: 15px;"></div>
            <div class="pagePost">

                <div class="container">

                    <div class="main">

                        <ul class="cbp_tmtimeline">

                            <?php

//                            var_dump($binding);die();

                            if(isset($binding))
                            {
                                arsort($binding);
                                foreach($binding as $node)
                                {
                            ?>
                                    <li id="scroll_<?=$node['actionid']?>">
                                        <time class="cbp_tmtime" datetime="

                                        <?php

                                        $timestamp = $node['createdtime'];
                                        echo date('Y-m-d h:s', $timestamp);
                                        ?>
                                        ">
                                            <span><?php echo date('d/m/Y', $timestamp) ?></span>
                                            <span><?php echo date('H:i', $timestamp) ?></span>
                                        </time>
                                        <div class="cbp_tmicon cbp_tmicon-earth"></div>
                                        <div class="cbp_tmlabel">
                                            <h2>
                                                <?php
                                                echo $pageInfo['bindingInfo']['pageName'];
                                                $typeAction = $node['content']['type'];
                                                if($typeAction == 'addStatus')
                                                {
                                                    echo " - cập nhật trạng thái";
                                                }
                                                elseif($typeAction=="changeAva")
                                                {
                                                    echo ' -  cập nhật ảnh đại diện';
                                                }
                                                elseif($typeAction=="changeLogo")
                                                {
                                                    echo ' -  cập nhật ảnh logo';
                                                }
                                                elseif($typeAction=="changeSlide")
                                                {
                                                    echo ' -  cập nhật slideshow ảnh nền';
                                                }
                                                elseif($typeAction=="addImage")
                                                {
                                                    echo ' -  thêm một ảnh mới';
                                                }
                                                elseif($typeAction=="addVideo")
                                                {
                                                    echo ' - thêm một video mới';
                                                }
                                                elseif($typeAction=="addSharePlace")
                                                {
                                                    echo ' - chia sẻ một địa điểm';
                                                }

                                                ?>
                                            </h2>
                                            <?php
                                            if($typeAction == 'addStatus')
                                            {
                                                echo '<p class="content_'.$node['actionid'].'">'.$node['content']['source'].'</p>';
                                            }
                                            elseif($typeAction == 'addImage' or $typeAction == 'changeSlide' or $typeAction=='changeLogo' or $typeAction=='changeAva')
                                            {
                                                echo '<p class="content_'.$node['actionid'].'">'.$node['content']['descript'] . '</p>';
                                                echo '<p>'.'<img src="'.$this->basePath().'/uploads/'.$node['content']['source'].'">'.'</p>';
                                            }
                                            elseif($typeAction == "addVideo")
                                            {
                                                echo '<p class="content_'.$node['actionid'].'">'.$node['content']['descript'] . '</p>';
//                                                    echo '<video id="example_video_1" class="video-js vjs-default-skin" controls preload="true" width="100%" height="318" poster="" data-setup="{}">';
//                                                    echo '<source src="'.$this->basePath().'/uploads/'.$node['content']['source'].'"';
//                                                    echo 'type="video/mp4"> </video>';
                                                echo '<p>'.'<video controls preload="true" poster="" data-setup="{}" style="width: 100%;">';
                                                echo '<source src="'.$this->basePath().'/uploads/'.$node['content']['source'].'"';
                                                echo 'type="video/mp4"> </video>' . '</p>';
                                            }
                                            elseif($typeAction == 'addSharePlace')
                                            {
                                                echo '<p>'.'<img src="'.$this->basePath().'/uploads/'.$node['content']['source'].'">' . '</p>';;
                                                echo '<p class="content_'.$node['actionid'].'">'.$node['content']['descript'].'</p>';
                                            }
                                            ?>
                                            <a href="<?='#scroll_'.$node['actionid']?>" id="<?php echo $node['actionid']; ?>" class="showInstanceCMT">Xem thêm bình luận</a>
                                            <?php if($checkRole == 'ADMIN' || $checkRole == 'MOD') {  ?><a class="deletePost" name="<?=$node['actionid']?>" href="">Xóa bài đăng</a> <?php } ?>
                                        </div>

                                    </li>

                            <?php
                                }
                            }
                            ?>

                            <li>
                                <time class="cbp_tmtime" datetime=""><span></span> <span></span></time>
                                <div class="cbp_tmicon cbp_tmicon-screen"></div>
                                <div class="cbp_tmlabel">
                                    <h2><?php echo $pageInfo['bindingInfo']['pageName'] ?></h2>
                                    <p>Được thành lập vào ngày
                                    <?php
                                    $dt = new DateTime();
                                    $dt->setTimestamp(substr($pageInfo['bindingInfo']['pageID'], 4));
                                    echo date_format($dt, 'd-m-Y');
                                    ?>
                                    <br>
                                        Đã gia nhập trang mạng fanpage của mạng xã hội du lịch và ẩm thực Zess.

                                    </p>
                                </div>
                            </li>
                        </ul>

                    </div>

                    <div class="absolute-comment" style="display: none;">
                        <div class="arrow_box">
                            <div class="close-arrowbox">Đóng</div>
                            <div class="toolComment" style="padding-top: 10px; padding-bottom: 10px;">
                                <ul>
                                    <li class="toolComment-Like" id="status_Like"><p id="text_btn_like">Thích</p>(<p id="count_Like">0</p>)</li>
                                    <li class="toolComment-cmt">Bình luận(<p id="count_Comment">0</p>)</li>
                                    <li class="toolComment-share" style="display: none;">Chia sẻ(0)</li>
                                </ul>
                            </div>

                            <div class="content-toolComment" id="notdelete" style="padding-bottom: 5px;">
                                <div class="avatar-memberComment" style="float: left;">
                                    <img id="<?php echo 'img_'.$masterID; ?>"
                                        name="<?php
                                    if(isset($avaWho['name'])) {
                                        echo $avaWho['name'];
                                    } else{
                                        echo  $pageInfo['bindingInfo']['pageName'];
                                    }  ?>"
                                         src="<?php
                                         if($checkRole == 'ADMIN' or $checkRole == 'MOD')
                                         {
                                             echo $this->basePath().'/uploads/' .$pageInfo['bindingImage']['imageAva'];
                                         }
                                         else{
                                             echo $this->basePath().'/uploads/'.$avaWho['pathAva'];
                                          }

                                         ?>" style="height: 100%; width: 100%;">
                                </div>
                                <div class="info-memberComment" style="float: left;width: 85%;padding-top: 5px;">
                                    <form method="post">
                                        <textarea class="commitComment" placeholder="nhập bình luận của bạn..."></textarea>
                                        <input class="btnCommitComment" type="submit" value="Đăng">
                                    </form>
                                </div>
                            </div>

                        </div>

                    </div>


                </div>

            </div>

        </div>



<!--       ACTIVITY OF MEMBER POST ON WALL -->
        <div class="page-member-activity">

            <div class="title-memberPost">
                <span>Bài đăng của những người khác lên tường <?php echo $pageInfo['bindingInfo']['pageName'] ?></span>
            </div>

            <?php

            function time_difference($date)
            {
                if(empty($date)) {
                    return "unidentifed";
                }
                $periods = array("giây", "phút", "giờ", "ngày", "tuần", "tháng", "năm", "thập kỷ");
                $lengths = array("60","60","24","7","4.35","12","10");
                $now = time();
                $unix_date = $date;
                if(empty($unix_date)) {
                    return "Bad date";
                }
                if($now > $unix_date) {
                    $difference = $now - $unix_date;
                    $tense = "trước"; } else {
                    $difference = $unix_date - $now;
                    $tense = "vừa mới";
                }
                for($j = 0; $difference >= $lengths[$j] && $j < count($lengths)-1; $j++) {
                    $difference /= $lengths[$j];
                }

                $difference = round($difference);

                if($difference != 1) {
                    $periods[$j].= " ";
                }
                return "$difference $periods[$j] {$tense}";
            }

            function getFullTime($date)
            {
                $value  = ' lúc '.date('H', $date). ' giờ ';
                $value .= date('i', $date) . ' phút';
                $value .= ' ngày '.date('d/m/Y', $date);
                return $value;
            }

            if(isset($userPost))
            {
//                var_dump($userPost);die();
                foreach($userPost as $node)
                {
            ?>

                    <div class="memberPost" id="postwall_<?=$node['statusid']?>">
                        <?php  if($checkRole == "ADMIN" || $checkRole == "MOD") { ?>
                        <div class="dele_post_onwall"  name="<?=$node['statusid']?>">X</div>
                        <?php } ?>
                        <div class="content-memberPost">
                            <div class="imageMember">
                                <img src="<?php echo $this->basePath().'/uploads/'. $node['pathava']; ?>">
                            </div>
                            <div class="infoMember">
                                <span class="nameMember">
                                    <a href="<?php echo $this->basePath().'/success?user='.$node['actionuser']; ?>">
                                        <?php echo $node['username']; ?>
                                    </a>
                                </span>
                                <span class="statusMember"><?php echo $node['statuscontent']; ?></span>
                        <span class="timepostMember">
                            <a href="#" title="<?php echo getFullTime($node['createdtime']); ?>">
                                <?php echo time_difference($node['createdtime']); ?>
                            </a>
                        </span>
                            </div>
                        </div>
                    </div>

            <?php
                }
            }
            else
            {
                echo '<p id="status_member_post">Hiện tại chưa có bài viết nào!</p>';
            }
            ?>





        </div>
    </div>

    <div style="height: 300px; width: 100%; float: left;"></div>

</section>

<footer>

</footer>

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/jquery.tmpl.min.js"></script>
<script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyAYVsGMEN8T8D9-TtSVgQQgM3ecNbYYFMw&sensor=false" type="text/javascript"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/jquery.mousewheel.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/jquery.jscrollpane.min.js"></script>


<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/mapalbum.js"></script>


<!--slide show logo and images-->
<script type="text/javascript">
    var windowHeight = jQuery(window).height();
    var windowWidth  = jQuery(window).width();

    jQuery(document).ready(function() {

        jQuery('.lightbox').slideUp(1500);

        jQuery('.page-cover > div:gt(0)').hide();
        setInterval(function() {
            jQuery('.page-cover > div:first')
                .fadeOut(1000)
                .next()
                .fadeIn(1000)
                .end()
                .appendTo('.page-cover');
        },  3000);
        setTimeout(function(){
            jQuery('#logo_change').attr('class', 'after-lightbox').animate({
                opacity:1,
                maxHeight: '200px'
            }, 2000);
            jQuery('.page-logo > img').css({
                'width': '100%',
                'height': 'auto'
            })
        }, 2000);

    });

</script>

<!--google maps-->
<script>

    function addInfoWindowHandle()
    {
        var divContent = document.createElement('div');
        divContent.id = "content";
        var divSiteNotice = document.createElement('div');
        divSiteNotice.id = "siteNotice";
        var tagH1 = document.createElement('h1');
        tagH1.id = "firstHeading";
        tagH1.className = "firstHeading";
        tagH1.textContent = "<?php echo $pageInfo['bindingInfo']['pageName'] ?>";
        var divBodyContent = document.createElement('div');
        divBodyContent.id = "bodyContent";
        var tagPre = document.createElement('p');
        jQuery(tagPre).text("<?php echo str_replace(array("\r\n","\r","\n"),' ',$pageInfo['bindingInfo']['pageMapInfo']); ?>");

        divContent.appendChild(divSiteNotice);
        divContent.appendChild(tagH1);
        divContent.appendChild(divBodyContent);
        divBodyContent.appendChild(tagPre);

        return divContent;
    }

    function initialize()
    {
        var pageLongt = <?php
        if(isset($pageInfo['bindingInfo']['pageLongt']))
            echo $pageInfo['bindingInfo']['pageLongt'];
         else
            echo 106.68617248535156;
        ?>;
        var pageLat = <?php
        if(isset($pageInfo['bindingInfo']['pageLat']))
            echo $pageInfo['bindingInfo']['pageLat'];
        else
            echo 10.779348472547026;
        ?>;
        var myLatlng = new google.maps.LatLng(pageLat,pageLongt);
        var mapProp = {
            center:myLatlng,
            zoom:15,
            scrollwheel: false,
            mapTypeId:google.maps.MapTypeId.ROADMAP
        };
        var map=new google.maps.Map(document.getElementById("mapToPageID")
            ,mapProp);

        var newImage = '<?php echo $this->basePath().'/img/icon-office-building.png' ?>';

        var marker = new google.maps.Marker({
            position: myLatlng,
            map: map,
            icon : newImage,
            title: "Nhấn để xem thông tin chi tiết!"
        });
        marker.setAnimation(google.maps.Animation.BOUNCE);



        var contentString = addInfoWindowHandle();
        var infoWindow = new google.maps.InfoWindow({
            content: contentString,
            maxWidth: 400
        });

        google.maps.event.addListener(marker, 'click', function() {
            infoWindow.open(map,marker);
        });

    }

    google.maps.event.addDomListener(window, 'load', initialize);

</script>

<!--logic page-->
<script type="text/javascript">

    jQuery(document).ready(function(){

        function getTimestampNow()
        {
            var datenow = new Date();
            datenow = parseInt(datenow.setFullYear(datenow.getFullYear(), datenow.getMonth(), datenow.getDate())/1000);
            return datenow;
        }

        ////////////////////START DELETE POST ON WALL FANPAGE///////////////////////////
        function deletePostOnWall(statusid)
        {
            var dataval = 'statusid='+statusid;
            var deleteID = '#postwall_'+statusid;
            jQuery.ajax({
                type: "POST",
                url: "<?php echo $this->url('fanpage', array('action' => 'deletepostonwall')); ?>",
                data: dataval,
                async:false,
                success: function(data) {
//                    alert(data);
                    data = jQuery.parseJSON(data);
                    if(data['success'] == 1)
                    {
                        jQuery(deleteID).animate({
                            opacity: 0,
                            height: 0
                        }, 1200, function(){
                            jQuery(this).remove();
                        });

                    }
                    else
                    {
                        alert('Xóa bài đăng thất bại!');
                    }
                },
                error: function() {
                    alert("Hệ thống đang bảo trì, xin hãy thử lại sau một ít phút nữa!");
                }
            });
        }

        jQuery('.dele_post_onwall').each(function(){
            jQuery(this).click(function(){
                var r=confirm('Đồng ý xóa bình luận trên tường của người này?');
                if(r==true){
                    var statusid = jQuery(this).attr('name');
                    deletePostOnWall(statusid);
                }
            });
        });
        ////////////////////END DELETE POST ON WALL FANPAGE/////////////////////////////

        //////////////////////////////////DELETE POST FANPAGE////////////////////////
        function deletePostFanpage(pageID, actionID, deleteID)
        {
            var dataval = 'actionID='+actionID+'&pageID='+pageID;
            jQuery.ajax({
                type: "POST",
                url: "<?php echo $this->url('fanpage', array('action' => 'deletefppost')); ?>",
                data: dataval,
                async:false,
                success: function(data) {
//                    alert(data);
                    data = jQuery.parseJSON(data);
                    if(data['success'] == 1)
                    {
                        jQuery(deleteID).animate({
                            opacity: 0,
                            height: 0
                        }, 1200, function(){
                            jQuery(this).remove();
                        });

                    }
                    else
                    {
                        alert('Xóa bài đăng thất bại!');
                    }
                },
                error: function() {
                    alert("Hệ thống đang bảo trì, xin hãy thử lại sau một ít phút nữa!");
                }
            });

        }

        jQuery('.deletePost').each(function(){
            jQuery(this).click(function(e){
                var r = confirm('Đồng ý xóa bài đăng này?');
                if(r==true)
                {
                    var actionID = jQuery(this).attr('name');
                    var deleteID = '#scroll_'+actionID;
                    var pageID = jQuery('#hidden-pageID').val();
                    deletePostFanpage(pageID, actionID, deleteID);
                }
                e.preventDefault();
            });
        });
        //////////////////////////////////END DELETE POST FANPAGE////////////////////

        //////////////////////////////////START LIKE PAGE///////////////////////////

        jQuery('#buttonLikePage').click(function(){
            var action = jQuery(this).attr('class');
            var userID = jQuery('#hidden-userIDNow').val();
            var pageID = jQuery('#hidden-pageID').val();
            var createdtime = getTimestampNow();

            var dataval="action="+action+"&userID="+userID+"&pageID="+pageID+"&createdtime="+createdtime;

//            alert(dataval);

            jQuery.ajax({
                type: "POST",
                url: "<?php echo $this->url('fanpage', array('action' => 'likepage')); ?>",
                data: dataval,
                async:false,
                success: function(data) {
//                    alert(data);
                    data = jQuery.parseJSON(data);
                    if(data['success'] == 1)
                    {
                        var divNumberLike = jQuery('#numberLike');
                        var value = parseInt(divNumberLike.text());
                        var buttonLike = jQuery('#buttonLikePage');

                        if(action == 'like')
                        {
                            value++;
                            divNumberLike.text(value);
                            buttonLike.attr('class', 'unlike');
                            buttonLike.text('Bỏ thích');
                        }
                        else
                        {
                            value--;
                            if(value <0 ) value = 0;
                            divNumberLike.text(value);
                            buttonLike.attr('class', 'like');
                            buttonLike.text('Thích');
                        }
                    }
                    else
                    {
                        alert('Thích fanpage thất bại!');
                    }
                },
                error: function() {
                    alert("Hệ thống đang bảo trì, xin hãy thử lại sau một ít phút nữa!");
                }
            });
        });

        //////////////////////////////////END LIKE PAGE/////////////////////////////

        /////////////////////////////////START SHARE PLACE///////////////////////////
        function createHashTag(str)
        {
            str = str.toLowerCase();
            str = str.replace(/à|á|ạ|ả|ã|â|ầ|ấ|ậ|ẩ|ẫ|ă|ằ|ắ|ặ|ẳ|ẵ/g, "a");
            str = str.replace(/è|é|ẹ|ẻ|ẽ|ê|ề|ế|ệ|ể|ễ/g, "e");
            str = str.replace(/ì|í|ị|ỉ|ĩ/g, "i");
            str = str.replace(/ò|ó|ọ|ỏ|õ|ô|ồ|ố|ộ|ổ|ỗ|ơ|ờ|ớ|ợ|ở|ỡ/g, "o");
            str = str.replace(/ù|ú|ụ|ủ|ũ|ư|ừ|ứ|ự|ử|ữ/g, "u");
            str = str.replace(/ỳ|ý|ỵ|ỷ|ỹ/g, "y");
            str = str.replace(/đ/g, "d");
            str = str.replace(/!|\$|\@|%|\^|\*|\(|\)|\+|\=|\<|\>|\?|\/|,|\.|\:|\;|\'| |\"|\&|\#|\[|\]|~|$|-/g, "_");
            //thay doi toan bo cac ki tu la trong chuoi
            str = str.replace(/_+_/g, "_"); //thay the 2 dau __ thanh 1_
            str = str.replace(/^\_+|\_+$/g, ""); // bo ki tu dau va cuoi chuoi
            return '#' +str;
        }

        jQuery('#post_share_button').click(function(){
            var pageID  = jQuery('#hidden-pageID').val();
            var timeStamp = getTimestampNow();
            var placeName = jQuery('#hashtag_share').val();
            var hashtag = createHashTag(placeName);
            var placeDescript = jQuery('#descript_share').val();

            var formdata  = new FormData(jQuery('#form_post_share')[0]);
            var reader = new FileReader();
            var value = reader.readAsDataURL(document.getElementById("btn_post_share").files[0]);

            formdata.append('image', value);
            formdata.append('timestamp', timeStamp);
            formdata.append('albumType', 'NOR');
            formdata.append('pageid', pageID);

            jQuery.ajax({
                type: "POST",
                url: "<?php echo $this->basePath().'/plugin/fanpage_upload.php' ;?>",
                data: formdata,
                cache: false,
                contentType: false,
                processData: false,
                async:false,
                success: function(data) {
//                    alert(data);
                    if(data!='error')
                    {
//                        alert('thanh cong');
                        saveNewSharePlace(data, pageID, timeStamp, placeName, placeDescript, hashtag);
                    }
                    else{
                        alert('Đăng chia sẻ địa điểm thất bại!');
                    }
                },
                error: function() {
                    alert("Hệ thống đang bảo trì, xin hãy thử lại sau một ít phút nữa!");
                }
            });
            return false;

        });

        function saveNewSharePlace(imagePath, pageID, timeStamp, placeName, placeDescript, hashtag)
        {
            var dataval = "imagePath="+imagePath+"&pageID="+pageID+"&timestamp="+timeStamp+"&placeName="+placeName+"&placeDescript="+placeDescript+"&hashtag="+hashtag;
//            alert(dataval);
            jQuery.ajax({
                type: "POST",
                url: "<?php echo $this->url('fanpage', array('action' => 'savenewshareplace')); ?>",
                data: dataval,
                async:false,
                success: function(data) {
//                    alert(data);
                    data = jQuery.parseJSON(data);
                    if(data['success'] == 1)
                    {
                        var headTitle = jQuery('.nameOfPage').text() + ' - đã chia sẻ một địa điểm';
                        var content = '<img src="<?php echo $this->basePath().'/uploads/';?>'+imagePath+'"></br>';
                        content += placeName+'</br>';
                        content += hashtag+'</br>';
                        content += placeDescript+'</br>';
                       instancePost(timeStamp, headTitle, content);
                    }
                    else
                    {
                        alert('Đăng chia sẻ địa điểm thất bại!');
                    }
                },
                error: function() {
                    alert("Hệ thống đang bảo trì, xin hãy thử lại sau một ít phút nữa!");
                }
            });
        }
        /////////////////////////////////END SHARE PLACE/////////////////////////////

        ////////////////////////////////START POST VIDEO /////////////////////////////
        jQuery('#post_upload_video').click(function(){
            var pageID  = jQuery('#hidden-pageID').val();
            var timeStamp = getTimestampNow();
            var descript = jQuery('#descript_upload_video').val();

            var formdata  = new FormData(jQuery('#form_upload_video')[0]);
            var reader = new FileReader();
            var value = reader.readAsDataURL(document.getElementById("btn_upload_video").files[0]);

            formdata.append('video', value);
            formdata.append('timestamp', timeStamp);
            formdata.append('userid', pageID);

            jQuery.ajax({
                type: "POST",
                url: "<?php echo $this->basePath().'/plugin/upload_video.php' ;?>",
                data: formdata,
                cache: false,
                contentType: false,
                processData: false,
                async:false,
                success: function(data) {
//                    alert(data);
                    if(data!='error')
                    {
                        saveNewVideo(data, pageID, timeStamp, descript);
                    }
                    else{
                        alert('Đăng video thất bại!');
                    }
                },
                error: function() {
                    alert("Hệ thống đang bảo trì, xin hãy thử lại sau một ít phút nữa!");
                }
            });
            return false;
        });

        function saveNewVideo(videoPath, pageID, timestamp, descript)
        {
            var dataval = "videoPath="+videoPath+"&pageID="+pageID+"&timestamp="+timestamp+"&descript="+descript;
//            alert(dataval);
            jQuery.ajax({
                type: "POST",
                url: "<?php echo $this->url('fanpage', array('action' => 'savenewvideo')); ?>",
                data: dataval,
                async:false,
                success: function(data) {
//                    alert(data);
                    data = jQuery.parseJSON(data);
                    if(data['success'] == 1)
                    {
                        var headTitle = jQuery('.nameOfPage').text() + ' - đã thêm một video mới';
                        var content = descript;
                        content += '<video id="example_video_1" class="video-js vjs-default-skin" controls preload="true" width="100%" height="318" poster="" data-setup="{}">';
                        content += '<source src="<?php echo $this->basePath().'/uploads/';?>' + videoPath + '" ';
                        content += 'type="video/mp4"> </video>';
                       instancePost(timestamp,headTitle, content);
                    }
                    else
                    {
                        alert('Đăng hình thất bại!');
                    }
                },
                error: function() {
                    alert("Hệ thống đang bảo trì, xin hãy thử lại sau một ít phút nữa!");
                }
            });
        }
        ////////////////////////////////END POST VIDEO /////////////////////////////

        ///////////////////////////////START POST IMAGE PAGE /////////////////////////
        jQuery('#post_image_page').click(function(){
            var albumType = "NOR";
            var pageID  = jQuery('#hidden-pageID').val();
            var timeStamp = getTimestampNow();
            var descript = jQuery('#descript_imagePage').val();

            var formdata  = new FormData(jQuery('#form_upload_imagePage')[0]);
            var reader = new FileReader();
            var value = reader.readAsDataURL(document.getElementById("btn_uploadImage_page").files[0]);

            formdata.append('image', value);
            formdata.append('timestamp', timeStamp);
            formdata.append('albumType', albumType);
            formdata.append('pageid', pageID);

            jQuery.ajax({
                type: "POST",
                url: "<?php echo $this->basePath().'/plugin/fanpage_upload.php' ;?>",
                data: formdata,
                cache: false,
                contentType: false,
                processData: false,
                async:false,
                success: function(data) {
                    if(data!='error')
                    {
//                        var imagePath = data;
                        saveNewImageforPage(data, pageID, timeStamp, descript);

                    }
                    else{
                        alert('Đăng hình thất bại!');
                    }
                },
                error: function() {
                    alert("Hệ thống đang bảo trì, xin hãy thử lại sau một ít phút nữa!");
                }
            });
            return false;

        });

        function saveNewImageforPage(imagePath, pageID, timestamp, descript)
        {
            var dataval = "imagePath="+imagePath+"&pageID="+pageID+"&timestamp="+timestamp+"&descript="+descript;
//            alert(dataval);
            jQuery.ajax({
                type: "POST",
                url: "<?php echo $this->url('fanpage', array('action' => 'savenewimage')); ?>",
                data: dataval,
                async:false,
                success: function(data) {
//                    alert(data);
                    data = jQuery.parseJSON(data);
                    if(data['success'] == 1)
                    {
                        var headTitle = jQuery('.nameOfPage').text() + ' - thêm một ảnh mới';
//                        alert(headTitle);
                        instancePost(timestamp, headTitle, '<?php echo '<img src=' . $this->basePath()."/uploads/";?>'+imagePath + '>');
                        jQuery('#form_upload_imagePage')[0].reset();
                    }
                    else
                    {
                        alert('Đăng hình thất bại!');
                    }
                },
                error: function() {
                    alert("Hệ thống đang bảo trì, xin hãy thử lại sau một ít phút nữa!");
                }
            });
        }

        ///////////////////////////////END POST IMAGE PAGE /////////////////////////



        function vainoiFunction(idofDivComment)
        {
            var e = document.getElementById(idofDivComment);
            var offset = {x:0,y:0};
            while (e)
            {
                offset.x += e.offsetLeft;
                offset.y += e.offsetTop;
                e = e.offsetParent;
            }

            if (document.documentElement && (document.documentElement.scrollTop || document.documentElement.scrollLeft))
            {
                offset.x -= document.documentElement.scrollLeft;
                offset.y -= document.documentElement.scrollTop;
            }
            else if (document.body && (document.body.scrollTop || document.body.scrollLeft))
            {
                offset.x -= document.body.scrollLeft;
                offset.y -= document.body.scrollTop;
            }
            else if (window.pageXOffset || window.pageYOffset)
            {
                offset.x -= window.pageXOffset;
                offset.y -= window.pageYOffset;
            }

//                    alert(offset.x + '\n' + offset.y);
            return offset.y;
        }

        jQuery('.titleTools>ul>li').each(function(){

            jQuery(this).click(function(){
                jQuery('.titleTools>ul>li').removeClass('menuNormal setmenuClicked').addClass('menuNormal');
                jQuery('.clickStatus').hide();
                jQuery(this).removeClass('menuNormal').addClass('setmenuClicked');

                var index = jQuery(this).index();
                if(index == 0){
                    jQuery('#firstBonnus').show();
                }
                else{
                    if(index == 1){
                        jQuery('#secoundBonnus').show();
                    }
                    else{
                        if(index == 2){
                            jQuery('#lastBonnus').show();
                        }else{
                            jQuery('#sharePlaceBonnus').show();
                        }
                    }
                }

            });
        });

        //small function for increase value of like, comment,..
        function increaseValue(locationid, sign, newID)
        {
            locationid = jQuery("'#" + locationid+"'");
            var valueNow = locationid.text();
            if(sign == "+")
            {
                valueNow = parseInt(valueNow) + 1;
            }
            else
            {
                valueNow = parseInt(valueNow) - 1;
                if(valueNow < 0)
                    valueNow = 0;
            }
            locationid.text(valueNow);
            locationid.attr('id', newID);
        }

        //LIKE ACTION: Status of page
        jQuery('.toolComment-Like').click(function(){
            var action = jQuery(this).attr('id'); // dafault value = status_Like;
            var actionUser = jQuery('#hidden-userIDNow').val();
            var actionLocation = jQuery('#hidden-pageID').val();
            var timestamp = getTimestampNow();
            var actionLike = jQuery(this).attr('name');

//            alert(action);

            var dataval = "action="+action+"&actionUser="+actionUser+"&actionLocation="+actionLocation+"&timestamp="+timestamp+"&actionLike="+actionLike;
            var dataUrl = "<?php echo $this->url('fanpage', array('action' => 'likestatusofpage')); ?>";
//            alert(dataUrl);
            if(action != "status_Like")
            {
                var likeID = jQuery('.toolComment-Like').attr('data-likeid');
                dataval = "action="+action+"&likeID="+likeID;
//                alert(dataval);
                dataUrl = "<?php echo $this->url('fanpage', array('action' => 'unlikestatusofpage')); ?>";
                dounlikeStatusPage(dataUrl, dataval);
            }
            else
            {
                dolikeStatusPage(dataUrl, dataval);
            }

            return false;
        });

        function dolikeStatusPage(dataUrl, dataval)
        {
            jQuery.ajax({
                type: "POST",
                url: dataUrl,
                data: dataval,
                async:false,
                success: function(data) {
//                    alert(data);
                    data = jQuery.parseJSON(data);
                    if(data['success'] == 1)
                    {
//                        alert('thanh cong->nhan ket qua');
                        var textLike  = jQuery('#text_btn_like');
                        var countLike = jQuery('#count_Like');
                        var valueNow = countLike.text();

                        jQuery('.toolComment-Like').attr('id', 'status_Unlike').addClass('hover_toolLike');
                        textLike.text('Bỏ thích');
                        valueNow = parseInt(valueNow) + 1;
                        countLike.text(valueNow);
                    }
                    else
                    {
                        alert('Thích trạng thái thất bại!');
                    }

                },
                error: function() {
                    alert("Hệ thống đang bảo trì, xin hãy thử lại sau một ít phút nữa!");
                }
            });
            return false;
        }

        function dounlikeStatusPage(dataUrl, dataval)
        {
            jQuery.ajax({
                type: "POST",
                url: dataUrl,
                data: dataval,
                async:false,
                success: function(data) {
//                    alert(data);
                    data = jQuery.parseJSON(data);
                    if(data['success'] == 1)
                    {
//                        alert('thanh cong->nhan ket qua');
                        var textLike  = jQuery('#text_btn_like');
                        var countLike = jQuery('#count_Like');
                        var valueNow = countLike.text();

                        jQuery('.toolComment-Like').attr('id', 'status_Like').removeClass('hover_toolLike');
                        textLike.text('Thích');

                        valueNow = parseInt(valueNow) - 1;
                        if(valueNow < 0)
                            valueNow = 0;

                        countLike.text(valueNow);
                    }
                    else
                    {
                        alert('Bỏ thích trạng thái thất bại!');
                    }
                },
                error: function() {
                    alert("Hệ thống đang bảo trì, xin hãy thử lại sau một ít phút nữa!");
                }
            });
            return false;
        }

        function loadCommentbyActID(actionID)
        {
            var checkUser = jQuery('#hidden-userIDNow').val();
            var dataval = "actionID="+actionID+"&checkUser="+checkUser;
//            alert(dataval);
            jQuery.ajax({
                type: "POST",
                url: "<?php echo $this->url('fanpage', array('action' => 'loadcommentbyid')); ?>",
                data: dataval,
                async:false,
                success: function(data) {
//                    alert(data);
                    data = jQuery.parseJSON(data);
                    deleteOldComment();
                    var toolLike = jQuery('.toolComment-Like');
                    toolLike.attr('id', 'status_Like');
                    if(data['success'] == 1)
                    {
                        var divAbsolute = jQuery('.absolute-comment');
                        var i = 0;
                        var maxi =0;
                        if(data['commentData'] != null)
                        {
                            maxi = data['commentData'].length;
                        }

                        //set value for count comments
                        jQuery('#count_Comment').text(maxi);

                        //set value for like, check liked?
                        var countLiked = data['checkLike']['countLiked'];
                        var userLiked = data['checkLike']['userLiked'];
                        var data_likeid = data['checkLike']['likeid'];

                        if(userLiked)
                        {
                            jQuery('#text_btn_like').text('Bỏ thích');
                            toolLike.addClass('hover_toolLike').attr('id', 'status_Unlike');
                            toolLike.attr('data-likeid', data_likeid);
                        }
                        else
                        {
                            jQuery('#text_btn_like').text('Thích');
                            toolLike.removeClass('hover_toolLike');
                        }

                        jQuery('#count_Like').text(countLiked);

                        function loopShowCMT()
                        {
                            if(i >= maxi)
                            {
                                return;
                            }
                            var linkAnh = '<?php echo $this->basePath().'/uploads/'; ?>' + data['commentData'][i]['avauser'];
                            var cmtContent = data['commentData'][i]['commentcontent'];
                            var nameUserPost = data['commentData'][i]['nameuser'];
                            instancePostComment(cmtContent, linkAnh, nameUserPost, data['commentData'][i]['createdtime'], 'none', data['commentData'][i]['actionuser']);
                            i++;
                            setTimeout(loopShowCMT, 400);
                        }
                        loopShowCMT();
                    }
                },
                error: function() {
                    alert("Hệ thống đang bảo trì, xin hãy thử lại sau một ít phút nữa!");
                }
            });
        }

        //close box arrow showed comments
        jQuery('.close-arrowbox').click(function(){
            var divShow = jQuery('.absolute-comment');
            var heightNow = divShow.css('height');
            var widthNow = divShow.css('width');
            divShow.animate({
                opacity:0,
                marginTop: '-30px'
            }, 1000, function(){
                jQuery(this).css({'display': 'none', 'opacity': 1, 'marginTop':0});
            });
        });



        //instance show comment
        jQuery('.showInstanceCMT').each(function(){
            jQuery(this).click(function(){
                showListComments(jQuery(this));
            });


        });

        function showListComments(jShowCmt)
        {
            var heightParent = jQuery(jShowCmt).parent().height();
            var idforShowCMT = jQuery(jShowCmt).attr('id');
            var posTop = vainoiFunction(idforShowCMT) - heightParent;
            var commentInstance = jQuery('.absolute-comment');
            var isDisplayorNor = commentInstance.css('display');

            //set actionID for like action
            jQuery('.toolComment-Like').attr('name', idforShowCMT);

//            alert('heightParent: ' + heightParent + ' , idforShowCMT: ' +idforShowCMT);

            //gan id cho div comment
            commentInstance.attr('id', idforShowCMT);

            //load data comments
            if(isDisplayorNor == "none")
            {
                commentInstance.css('top', posTop);
            }
            if(heightParent < 215)
            {
                heightParent = 215;
            }

            commentInstance.fadeIn(1000);
            commentInstance.animate({
                top: posTop,
                height: heightParent
            }, 1200, function(){
                loadCommentbyActID(idforShowCMT);
            });

        }

        //btn post comment
        jQuery('.btnCommitComment').click(function(){
            clickShowComment();
            return false;
        });

        function clickShowComment()
        {
            var time = getTimestampNow();
            var actionID = jQuery('.absolute-comment').attr('id');
            var contentComt = jQuery('.commitComment');
            var valueComt = contentComt.val();
            var actionLocation = jQuery('#hidden-pageID').val();
            var actionUser = jQuery('#hidden-userIDNow').val();
            if(valueComt.length == 0)
            {
                alert('Bạn chưa nhập nội dung bình luận của mình!');
                contentComt.focus();
            }
            else
            {
                insertNewComment(actionID, actionUser, actionLocation, valueComt, time);
            }

            return false;
        }

        function insertNewComment(actionID, actionUser, actionLocation, cmtContent, createdTime)
        {
            var dataval = "actionID="+actionID+"&actionUser="+actionUser+"&actionLocation="+actionLocation+"&cmtContent="+cmtContent+"&createdTime="+createdTime;

            jQuery.ajax({
                type: "POST",
                url: "<?php echo $this->url('fanpage', array('action' => 'insertnewcomment')); ?>",
                data: dataval,
                async:false,
                success: function(data) {
                    data = jQuery.parseJSON(data);
                    if(data['success'] == 1)
                    {
                        var linkAnh = "<?php
                        echo $this->basePath().'/uploads/';
                        if($pageID != $masterID)
                        {
                           if(isset($avaWho['pathAva']))echo $avaWho['pathAva'];
                        }
                        else
                        {
                           if(isset($pageInfo['bindingImage']['imageAva'])) echo $pageInfo['bindingImage']['imageAva'];
                        }
                        ?>";
                        var nameUserPost = jQuery('#img_'+actionUser).attr('name');
                        instancePostComment(cmtContent, linkAnh, nameUserPost, createdTime, 'instance', actionUser);

                        //delete content in comment box
                        jQuery('.commitComment').val('');
                        //increase count_Comment
                        var countLike = jQuery('#count_Comment');
                        var newValue = parseInt(countLike.text()) + 1;
//                        alert(newValue);
                        countLike.text(newValue);
                    }
                },
                error: function() {
                    alert("Hệ thống đang bảo trì, xin hãy thử lại sau một ít phút nữa!");
                }
            });
        }



        function instancePostComment(cmtContent, linkAvatar, nameUserPost, createdTime ,typeComment, ID)
        {
            var newDate = new Date(createdTime*1000);
            var timeConvert = ' lúc ' + newDate.getHours()+':'+newDate.getMinutes();
            var dateConvert = ' ngày ' + newDate.getDate()+'/'+(newDate.getMonth()+1)+'/'+newDate.getFullYear();
            var timePost ="";
            if(typeComment == 'instance')
            {
                timePost = " vài giây trước"
            }
            else
            {
                timePost = timeConvert + dateConvert;
            }

            var divToolComment = document.createElement('div');
            divToolComment.className = "content-toolComment";
            divToolComment.id = "delcmt_CMT" + ID + createdTime;

            var divAvatar = document.createElement('div');
            divAvatar.className = "avatar-memberComment";

            var imgAvatar = document.createElement('img');
            jQuery(imgAvatar).attr('src', linkAvatar);

            var divInfoMem = document.createElement('div');
            divInfoMem.className = 'info-memberComment';

            var tagANameMem = document.createElement('a');
            tagANameMem.className = "name-membercmt";

            var tagSpanofName = document.createElement('span');
            tagSpanofName.textContent = nameUserPost;

            var tagAcontentCmt = document.createElement('a');
            tagAcontentCmt.className = "countlike-membercmt";

            var tagASpanofContent = document.createElement('span');
            tagASpanofContent.textContent = cmtContent;

            var tagSpanofLikeButton = document.createElement('span');
            tagSpanofLikeButton.className = "like-time-membercmt";

            var tagAofSpanofLikeButton = document.createElement('a');
//            tagAofSpanofLikeButton.textContent = "Thích(0)";



            divToolComment.appendChild(divAvatar);
                divAvatar.appendChild(imgAvatar);
            divToolComment.appendChild(divInfoMem);
                divInfoMem.appendChild(tagANameMem);
                    tagANameMem.appendChild(tagSpanofName);
                divInfoMem.appendChild(tagAcontentCmt);
                    tagAcontentCmt.appendChild(tagASpanofContent);
                divInfoMem.appendChild(tagSpanofLikeButton);
                    tagSpanofLikeButton.appendChild(tagAofSpanofLikeButton);
                    jQuery(tagSpanofLikeButton).append(timePost);

            var checkRole = "<?php if($checkRole == 'ADMIN' || $checkRole == 'MOD') echo true; ?>";

            if(checkRole == true){
                var divDeleComment = document.createElement('div');
                divDeleComment.className = "delete_comment";
                divDeleComment.textContent = "X";

                jQuery(divDeleComment).attr('name','CMT'+ID+createdTime);
                divToolComment.appendChild(divDeleComment);

                jQuery(divDeleComment).each(function(){
                    jQuery(this).click(function(){
                        var r = confirm('Xóa bình luận này ?');
                        if(r == true){
                            var xyz = jQuery(this).attr('name');
                            var divID = '#delcmt_' + xyz;
                            deleteCommentOnPost(xyz, divID);
                        }
                    });
                });
            }

            jQuery(divToolComment).css('opacity', 0);
            jQuery('.toolComment').after(divToolComment);
//            jQuery(divToolComment).slideDown(400);
            jQuery(divToolComment).animate({
                opacity:1
            },600);
            jQuery('.absolute-comment').css('height', 'auto');


        }

        function deleteCommentOnPost(commentID, divID)
        {
            var dataval = "commentID=" + commentID;
            jQuery.ajax({
                type: "POST",
                url: "<?php echo $this->url('fanpage', array('action' => 'deletecommentonpost')); ?>",
                data: dataval,
                async:false,
                success: function(data) {
                    data = jQuery.parseJSON(data);
                    if(data['success'] == 1)
                    {
                        jQuery(divID).animate({
                            opacity: 0,
                            height: 0
                        }, 1200, function(){
                            jQuery(this).remove();
                        });
                    }
                },
                error: function() {
                    alert("Hệ thống đang bảo trì, xin hãy thử lại sau một ít phút nữa!");
                }
            });

        }

        function deleteOldComment()
        {
            jQuery('.content-toolComment').each(function(){
                var checkDel = jQuery(this).attr('id');
                if(checkDel != 'notdelete')
                {
                    jQuery(this).hide(600);
                    jQuery(this).remove();
                }
            });
        }

        //////////////////////////START POST STATUS OF PAGE////////////////////////////


        function instancePost(createTime, headTitle, content)
        {
            var newDate = new Date(createTime*1000);
            var timeConvert = newDate.getHours()+':'+newDate.getMinutes();
            var dateConvert = newDate.getDate()+'/'+(newDate.getMonth()+1)+'/'+newDate.getFullYear();
//            alert(timeConvert + '  ' + dateConvert );

            var tagLi = document.createElement('li');
            tagLi.id = "scroll_ACT"+createTime;

            var tagTime = document.createElement('time');
            tagTime.className = "cbp_tmtime";
            tagTime.dateTime = dateConvert + ' ' + timeConvert;

            var tagSpan1 = document.createElement('span');
            tagSpan1.textContent = dateConvert;

            var tagSpan2 = document.createElement('span');
            tagSpan2.textContent = timeConvert;

            var divIcon = document.createElement('div');
            divIcon.className = "cbp_tmicon cbp_tmicon-earth";

            var divContent = document.createElement('div');
            divContent.className = "cbp_tmlabel";

            var tagH2 = document.createElement('h2');
            tagH2.textContent = headTitle;

            var tagP = document.createElement('p');
            jQuery(tagP).html(content);

            var tagaShowComment = document.createElement('a');
            tagaShowComment.className = "showInstanceCMT";
            tagaShowComment.id = "ACT" + createTime;
            tagaShowComment.textContent = "Xem thêm bình luận";

            var tagaDeletePost = document.createElement('a');
            tagaDeletePost.className = "deletePost";
            tagaDeletePost.name = "ACT"+createTime;
            tagaDeletePost.href = "";
            tagaDeletePost.textContent = "Xóa bài đăng";

            tagLi.appendChild(tagTime);
                tagTime.appendChild(tagSpan1);
                tagTime.appendChild(tagSpan2);
            tagLi.appendChild(divIcon);
            tagLi.appendChild(divContent);
                divContent.appendChild(tagH2);
                divContent.appendChild(tagP);
                divContent.appendChild(tagaShowComment);
                divContent.appendChild(tagaDeletePost);

            jQuery(tagLi).css({'margin-top':'-123px', 'margin-bottom': '123px', 'opacity': 0, 'position': 'relative'});
            jQuery('ul.cbp_tmtimeline').prepend(tagLi);
            jQuery(tagLi).animate({
                marginTop: '0px',
                marginBottom: '0px',
                opacity: 1
            }, 2000);

//            //register button show list comment
            jQuery(tagaShowComment).each(function(){
                jQuery(this).click(function(){
                    showListComments(jQuery(this));
                });
            });

            jQuery(tagaDeletePost).each(function(){
                jQuery(this).click(function(){
                    var r = confirm('Đồng ý xóa bài đăng này?');
                    if(r==true)
                    {
                        var actionID = 'ACT'+createTime;
                        var deleteID = '#scroll_'+actionID;
                        var pageID = jQuery('#hidden-pageID').val();
                        deletePostFanpage(pageID, actionID, deleteID);
                    }
                    return false;
                });
            });

        }

        function userPostStatus(content, userID, imagePath, username)
        {
            var divmemberPost = document.createElement('div');
            divmemberPost.className = "memberPost";

            var divContentPost = document.createElement('div');
            divContentPost.className = "content-memberPost";

            var divimageMember = document.createElement('div');
            divimageMember.className = "imageMember";

            var imgImageMember = document.createElement('img');
            jQuery(imgImageMember).attr('src', imagePath);

            var divInfoMember = document.createElement('div');
            divInfoMember.className = "infoMember";

            var spanNameMember = document.createElement('span');
            spanNameMember.className = "nameMember";

            var tagALinkMember = document.createElement('a');
            jQuery(tagALinkMember).attr('href', '<?php echo $this->basePath().'/success?user=';?>' + userID);
            tagALinkMember.textContent = username;

            var spanStatusMember = document.createElement('span');
            spanStatusMember.className = "statusMember";
            spanStatusMember.textContent = content;

            var spanTimepostMember = document.createElement('span');
            spanTimepostMember.className = "timepostMember";

            var tagATimepostMember = document.createElement('a');
            jQuery(tagATimepostMember).attr('href', '#');
            tagATimepostMember.title = " vài giây trước";
            tagATimepostMember.textContent = " vài giây trước";

            divmemberPost.appendChild(divContentPost);
                divContentPost.appendChild(divimageMember);
                    divimageMember.appendChild(imgImageMember);
                divContentPost.appendChild(divInfoMember);
                    divInfoMember.appendChild(spanNameMember);
                        spanNameMember.appendChild(tagALinkMember);
                    divInfoMember.appendChild(spanStatusMember);
                    divInfoMember.appendChild(spanTimepostMember);
                        spanTimepostMember.appendChild(tagATimepostMember);
            jQuery(divContentPost).css('opacity', 0);
            jQuery('.title-memberPost').after(divmemberPost);
            jQuery(divContentPost).animate({
                opacity: 1
            }, 1000);
        }

        jQuery('#btn_post_status').click(function(){
            //error_post_status
            var content_status = jQuery('#cnt_page_status').val();
            var userNow = jQuery('#hidden-userIDNow').val();
            var pageID = jQuery('#hidden-pageID').val();
            var createdTime = getTimestampNow();
                if(content_status.length == 0 || content_status.length < 6)
                {
                    jQuery('#error_post_status').text('Nội dung trạng thái không được bỏ trống hoặc phải có ít nhất 6 kí tự!').show(600).delay(4000).hide(400);
                }
                else
                {
                    var dataval = "userNow="+userNow+"&pageID="+pageID+"&statusContent="+content_status+"&createdTime="+createdTime;
//                    alert(dataval);

                    jQuery.ajax({
                        type: "POST",
                        url: "<?php echo $this->url('fanpage', array('action' => 'insertpagestatus')); ?>",
                        data: dataval,
                        async:false,
                        success: function(data) {
                            data = jQuery.parseJSON(data);
                            if(data['success'] == 1)
                            {
                                if(pageID == userNow)
                                {
                                    instancePost(createdTime, '<?php echo $pageInfo['bindingInfo']['pageName'] ?>', content_status);
                                }
                                else
                                {
                                    jQuery('#status_member_post').remove();
                                    var linkImg =  "<?php echo $this->basePath().'/uploads/';
                                    if(isset($avaWho['pathAva'])) echo $avaWho['pathAva']; ?>";
                                    var nameUserPost = jQuery('#img_'+userNow).attr('name');
                                    userPostStatus(content_status, userNow, linkImg, nameUserPost);
                                }

                                jQuery('#form-pagePostStatus')[0].reset();
                            }
                        },
                        error: function() {
                            alert("Hệ thống đang bảo trì, xin hãy thử lại sau một ít phút nữa!");
                        }
                    });


                }
            return false;
        });
        //////////////////////////END POST STATUS OF PAGE////////////////////////////

    });
</script>