<noscript>
    <style>
        .es-carousel ul{
            display:block;
        }

    </style>
</noscript>
<script id="img-wrapper-tmpl" type="text/x-jquery-tmpl">
    <div class="rg-image-wrapper">
        {{if itemsCount > 1}}
        <div class="rg-image-nav">
            <a href="#" class="rg-image-nav-prev">Previous Image</a>
            <a href="#" class="rg-image-nav-next">Next Image</a>
        </div>
        {{/if}}
        <div class="rg-image">
            <div id="imageContent">abc</div>
        </div>
        <div class="rg-loading"></div>
        <div class="rg-caption-wrapper">
            <div class="rg-caption" style="display:none;">
                <img src="<?php echo $this->basePath().'/img/quote.png' ?>" style="width:16px; height:16px;">
                <p style="display:inline-block;"></p>
            </div>

            <div class="imageContent">


            </div>
        </div>
    </div>
</script>




<div class="container">
    <div class="content">
        <h1 style="color: black;">
            <?php
                if(isset($listAvatar))
                {
                    echo 'Album ảnh đại diện đã thay đổi ('.count($listAvatar).' ảnh)';
                }
                elseif(isset($listCover))
                {
                    echo 'Album ảnh nền đã thay đổi (' . count($listCover).' ảnh)';
                }
                elseif(isset($listNormal))
                {
                    echo 'Album ảnh đã tải lên (' . count($listNormal).' ảnh)';
                }
                else echo 'Hiện tại chưa có ảnh nào.';
            ?>
        </h1>

        <?php
        $nodes = null;
        if(isset($listAvatar))
        {
            $nodes = $listAvatar;
        }
        elseif(isset($listNormal))
        {
            $nodes = $listNormal;
        }
        elseif(isset($listCover))
        {
            $nodes = $listCover;
        }


        if($nodes != null)
        {

        ?>

        <div id="rg-gallery" class="rg-gallery">
            <div class="rg-thumbs">
                <div class="es-carousel-wrapper">
                    <div class="es-nav">
                        <span class="es-nav-prev">Previous</span>
                        <span class="es-nav-next">Next</span>
                    </div>
                    <div class="es-carousel">
                        <ul>
                            <?php

                                foreach($nodes as $node)
                                {
                                    echo '<li>';
                                    echo '<a href>';
                                    echo '<img src="'.$this->basePath().'/uploads/'.$node['imagePath'].'" ';
                                    echo 'data-large="'.$this->basePath().'/uploads/'.$node['imagePath'].'" ';
                                    echo 'data-description="'.$node['imageDescript'].'">';
                                    echo '</a>';
                                    echo '</li>';
                                }

                            ?>

                        </ul>
                    </div>
                </div>
                <!-- End Elastislide Carousel Thumbnail Viewer -->
            </div><!-- rg-thumbs -->
        </div><!-- rg-gallery -->

        <?php

        }
        ?>


    </div><!-- content -->
</div><!-- container -->