<br>
<br>
<br>
<div style="margin-left: 100px;">
    <form method="post">
        <input type="text" id="firstname" placeholder="Nhập Tên...">
        <input type="text" id="lastname" placeholder="Nhập Họ...">
        <input type="text" id="userid" placeholder="User ID...">
        <input type="button" id="insert" value="Insert">
    </form>
</div>

<div style="margin-top: 30px; margin-left: 100px;">
    <input type="button" id="select" value="Select">
    <div id="resultContent"></div>
</div>

<div style="margin-top: 30px; margin-left: 100px;">
    <input type="text" id="useriddelete" placeholder="UserID...">
    <input type="button" id="delete" value="Delete">
    <div id="deletecontent"></div>
</div>

<hr style="width: 1000px;height: 2px; border: 3px solid black;">
<br>

<div style="width: 100%; height: 1000px;    "></div>

<script type="text/javascript">
    jQuery(document).ready(function(){

        jQuery(window).scroll(function(){
            if(jQuery(window).scrollTop() == jQuery(document).height() - jQuery(window).height()){
               alert('load du lieu moi');
            }
        });


        //Click vao Insert
        jQuery('#insert').click(function(){
            var firstname = jQuery('#firstname').val();
            var lastname = jQuery('#lastname').val();
            var userid = jQuery('#userid').val();
            var data = "firstname=" + firstname + "&lastname=" + lastname + '&userid=' + userid;
            jQuery.ajax({
                type: "POST",
                url: "<?php echo $this->url('example', array('action' => 'insert')); ?>",
                data: data,
                async:false,
                success: function(data) {
                    data = JSON.parse(data);

                    if(data['success'] == "1")
                    {
                        jQuery('#firstname').val('');
                        jQuery('#lastname').val('');
                        jQuery('#userid').val('');
                    }
                    else
                    {
                        alert('Insert that bai');
                    }

                },
                error: function() {
                    alert("Hệ thống đang bảo trì, xin hãy thử lại sau một ít phút nữa!");
                }
            });
            return false;

        });


        //Click vao show thong tin vua insert ra
        jQuery('#dfdsf').click(function(){

            var data = "";
            alert(data);
            jQuery.ajax({
                type: "POST",
                url: "<?php echo $this->url('example', array('action' => 'select')); ?>",
                data: data,
                async:false,
                success: function(data) {
                    data = JSON.parse(data);

                    if(data['success'] == "1")
                    {
                        alert('select thanh cong, chuan bị in giá trị ra');
                        jQuery('#resultContent').text(data['value']); //day la bien truyen tu ben Controller
                    }
                    else
                    {
                        alert('select that bai');
                    }

                },
                error: function() {
                    alert("H? th?ng ?ang b?o trì, xin hãy th? l?i sau m?t ít phút n?a!");
                }
            });
            return false;
        });

        jQuery('#select').on('click', function() {
            jQuery.ajax({
               url: '<?php echo $this->url('example', array('action' => 'select')); ?>',
               type: 'post',
               data: '',
               async: false,
               success: function(data) {
                   data = JSON.parse(data);
                   if (data['success'] == 1) {
                       jQuery('#resultContent').html(data['fristname']);
                   }
               },
               error: function(data) {
                   alert('loi');
               }
            });
        });

        jQuery('#delete').on('click', function() {
            var userid =  jQuery('#useriddelete').val();
            var data = 'userid=' + userid;

            jQuery.ajax({
                url: '<?php echo $this->url("example", array("action" => "delete")) ?>',
                type: 'post',
                data: data,
                async:false,
                success: function(data) {
                    data = JSON.parse(data);
                    if (data['success'] == 1) {
                        jQuery('#deletecontent').html('thanh cong');
                        jQuery('#useriddelete').val('');
                    }
                },
                error: function(data) {
                    alert('loi');
                }
            });
        });

    });
</script>