<style type="text/css">

    .logoZess:hover{
        text-decoration: none;
    }
    .statusType > div {
        cursor: pointer;
    }
    pre {
        font-family: "Roboto Slab", Tahoma !important;
        border:none;
    }

</style>

<script type="text/javascript">
    jQuery('body').addClass('bodyUserpage');
    jQuery('html').addClass('bodyUserpage');
</script>


<?php

// Time Difference
function time_difference($date)
{
 if(empty($date)) {
 return "unidentifed";
 }
 $periods = array("giây", "phút", "giờ", "ngày", "tuần", "tháng", "năm", "thập kỷ");
 $lengths = array("60","60","24","7","4.35","12","10");
 $now = time();
// $unix_date = strtotime($date);
 $unix_date = $date;
 // Check validity of date

 if(empty($unix_date)) {
 return "Bad date";

 }
 // Determine tense of date

 if($now > $unix_date) {
 $difference = $now - $unix_date;
 $tense = "trước"; } else {
 $difference = $unix_date - $now;
 $tense = "vừa mới";
 }
 for($j = 0; $difference >= $lengths[$j] && $j < count($lengths)-1; $j++) {
 $difference /= $lengths[$j];
 }

 $difference = round($difference);

 if($difference != 1) {
   $periods[$j].= " ";
   }
  return "$difference $periods[$j] {$tense}";
}

//$date = 1387114483;
//$result = time_difference($date);
//echo $result;
//die();

?>


<input type="hidden" id="userID" value="<?php echo $datauser->getUserid(); ?>">

<div class="divLeft">
    <div class="divSubMenu">
        <a class="logoZess" style="width: 100%;" href="<?php echo $this->basePath(); ?>/">
<!--            <div class="divLogo">ZESS</div>-->
            <div style="padding: 10px 0px 5px 50px; width: 100%;">
                <img style="width: 60%;height: 60%;" src="<?php echo $this->basePath();?>/img/zess_logo2.png">
            </div>
        </a>
        <div class="divSearch">
            <form method="post" id="searchEverything">
                <input id="txtSearch" type="text" placeholder="Tìm kiếm mọi thứ ..." />
                <input id="btnSearch" type="button" value=" " />
            </form>

            <style type="text/css">
                    #searchResult{background-color: #E5E5E5; width: 304px; height: auto; position: absolute; margin-top: 39px;
                            padding-top: 5px; padding-bottom: 5px; border-bottom-left-radius: 7px; border-bottom-right-radius: 7px;
                        box-shadow: 0 3px 3px rgba(0, 0, 0, 0.7), inset 0 2px 2px rgba(255, 255, 255, 0.5);
                        border: 1px solid #1E9DF9; border-left: 2px solid #1FA3FF; border-right: 2px solid #1FA3FF;}
                .searchUser{ padding: 2px 5px 0 5px; border-bottom: 1px solid #1FA3FF;}
                .searchUser :hover { }
                .image-searchUser{display: inline-block;}
                .image-searchUser > img{width: 50px; height: 50px; vertical-align: baseline; border-radius: 10px;}
                .content-searchUser{display: inline-block; padding-left: 8px;}
                .content-searchUser a{ cursor: pointer;}
                .content-searchUser a span{display: block; color: #000000;}
                .name-searchUser{font-size: 13px;}
                .banchung-searchUser{ font-size: 12px;}
                .btnKetban-searchUser, .btnKetban-copy{font-size: 11px;}
                .readmore{ font-size: 12px; cursor: pointer; display: block; text-align: center;
                padding-top: 5px; padding-bottom: 5px;}
                .newBackground{background: -webkit-linear-gradient(top, rgba(179,220,237,1) 0%,rgba(41,184,229,1) 50%,rgba(188,224,238,1) 100%); /* Chrome10+,Safari5.1+ */}
            </style>

            <div id="searchResult" style="display: none;">
                <div class="searchUser">
                    <div class="image-searchUser">
                        <img src="<?php echo $this->basePath(); ?>/img/avatar.jpg" >
                    </div>
                    <div class="content-searchUser">
                        <a href="#"><span class="name-searchUser">Nguyễn Phúc Hưng</span></a>
                        <a href="#"><span class="banchung-searchUser" >4 bạn chung</span></a>
                        <a href="#" name=""><span class="btnKetban-searchUser">Kết bạn</span></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="divSub about">
            <div class="divHead">Giới thiệu bản thân</div>
            <div class="divContent">
                <div class="aboutImg job">
                </div>
                <div class="aboutInfo">
                    <?php
                        if($datauser->getSchool() != null)
                        {
                            echo $datauser->getSchool();
                        }
                        else
                        {
                            echo "Chưa cập nhật.";
                        }
                    ?>
                </div>
            </div>
            <div class="divContent">
                <div class="aboutImg study">
                </div>
                <div class="aboutInfo">
                    <?php
                    if($datauser->getWork() != null)
                    {
                        echo $datauser->getWork();
                    }
                    else
                    {
                        echo "Chưa cập nhật";
                    }
                    ?>
                </div>
            </div>
            <div class="divContent">
                <div class="aboutImg relationship">
                </div>
                <div class="aboutInfo">
                    <?php
                    if($datauser->getRelationship() != null)
                    {
                        echo $datauser->getRelationship();
                    }
                    else
                    {
                        echo "Chưa cập nhật.";
                    }
                    ?>
                </div>
            </div>
        </div>
        <div class="divSub friend">
            <a href="
            <?php
                if($actionUserID == $actionLocationID)
                    echo $this->basePath().'/success/friend/';
                else
                    echo $this->basePath().'/success/friend?user='.$actionLocationID;

            ?>">
                <div class="divHead"> Bạn bè </div>
            </a>
            <div class="divContent" id="listF" style="overflow-y: scroll;max-height: 214px;">

                <style type="text/css">
                    #listF .subImage img { width: 50px; border-radius: 10px;}
                    #listF .subImage img:hover{ cursor: pointer}
                    #listF a :hover{
                        cursor: pointer;
                        color: #020202;
                    }
                    #listF .subImage label{font-weight: normal !important;}
                    #listF .subImage :hover{font-weight: bold !important; ;}
                </style>

                <?php
                if($listFriendAccepted != null)
                {
//                    var_dump($listFriendID);die();
                    foreach($listFriendAccepted as $friendID)
                    {

                ?>
                    <a href="<?php echo $this->basePath().'/success?user='.$friendID;?>">
                        <div class="subImage" >
                            <img src="<?php echo $this->basePath().'/uploads/'.$listFriendID['infoFriends'][$friendID]['pathAvatar']; ?>"
                                 alt="">
                            <label style="font-size: 13px; margin-left: 25px;"><?php echo $listFriendID['infoFriends'][$friendID]['fullname']; ?></label>
                        </div>
                    </a>

                <?php
                    }
                }
                else{
                    echo "Hiện tại chưa có bạn bè nào.";
                }

                ?>
            </div>
        </div>
        <div class="divSub photo">
            <a href="<?php
            if($actionUserID == $actionLocationID)
                echo $this->basePath().'/photos/';
            else
                echo $this->basePath().'/photos?user='.$actionLocationID;
            ?>">
                <div class="divHead"> Album ảnh & Video </div>
            </a>
            <style type="text/css">
                #listPics .subImage:hover{background: none;}
                #listPics .subImage img {width: 180px; border-radius: 10px; position: relative;}
                .wrapper-slide {height: 190px;overflow: hidden;width: 183px;margin-left: 55px;}
                .slide-avar{position: relative;}
                .slide-avar div{ display: inline-block}
                .slide-avar div img:hover{cursor: pointer;}

            </style>
            <div class="divContent" id="listPics">

               <div class="subImage" id="trigger-ava">
                   <label style="font-weight: normal;">Ảnh đại diện thay đổi gần đây</label>

                   <?php
                   if($albumAvatarHome != null)
                   {
                   ?>

                   <div class="left-slide-arrow"></div>
                   <div class="wrapper-slide" style="width: 180px;">
                        <div class="slide-avar">
                            <?php
                                foreach($albumAvatarHome as $image)
                                {
                           ?>
                           <div class="small-div">
                               <img src="<?php echo $this->basePath().'/uploads/'.$image;?>">
                           </div>
                           <?php
                                }
                            ?>
                           </div>
                   </div>
                   <div class="right-slide-arrow"></div>

                       <?php
                    }
                   else
                   {
                       echo "</br>Chưa cập nhật ảnh đại diện.";
                   }

                   ?>

               </div>



                <div class="subImage" style="margin-top: 10px; padding-left: 15px; margin-bottom: 10px; padding-bottom: 10px;">
                    <a href="<?php
                    if($actionUserID == $actionLocationID)
                        echo $this->basePath().'/photos/normal/';
                    else
                        echo $this->basePath().'/photos/normal?user='.$actionLocationID;
                    ?>">
                        Xem thêm các album khác ...
                    </a>
                </div>

            </div>

            <script type="text/javascript">

                    var currIndex = 0;
                    var slideStep = 182;
                    var maxItems;
                    var waitingTime = 0;
//                    alert(maxItems);

                    function moveLeft()
                    {
//                        alert(currIndex);
                        if(currIndex == 0)
                        {
                            currIndex = maxItems;
                        }
                        currIndex -= 1;
                        if(currIndex < 0)
                        {
                            currIndex = 0;
                        }
                        move(currIndex);
                    }
                    function moveRight()
                    {
//                        alert(currIndex);
                        waitingTime++;
                        if(waitingTime<5)
                        {
                            return;
                        }
                        waitingTime = 0;
                        if(currIndex == maxItems - 1)
                        {
                            currIndex = -1;
                        }
                        currIndex += 1;
                        if(currIndex > maxItems -1)
                        {
                            currIndex = maxItems -1;
                        }
                        move(currIndex);
                    }

                    function move(index)
                    {
                        jQuery('.slide-avar').animate({'left': -(index*slideStep)}, 500, function(){

                        });
                    }

                    function onClickLeft()
                    {
                        waitingTime = 0;
                        moveLeft();
                    }
                    function onClickRight()
                    {
                        waitingTime = 5;
                        moveRight();
                    }

                jQuery(document).ready(function(){
                    jQuery(document).trigger('trigger-ava');
                    maxItems = jQuery('.slide-avar .small-div').length;

                    var longDiv= maxItems*slideStep+maxItems*3;
                    jQuery('.slide-avar').css('width',longDiv+ "px");

                    jQuery('.slide-avar .small-div img').hover(function(){
                        waitingTime=0;
                    });

                    jQuery('.right-slide-arrow').click(onClickRight);
                    jQuery('.left-slide-arrow').click(onClickLeft);

                    setInterval('moveRight();', 1000);

                    jQuery(document).trigger("bind");
                });

            </script>

        </div>
    </div>

    <div class="divMenu">
        <a href="<?php echo $this->basePath().'/homepage/'; ?>">
            <div class="menuSub home">
                <div class="divMenuIcon home"></div>
                <div class="divMenuName home">Trang chủ</div>
            </div>
        </a>
        <a href="<?php echo $this->basePath().'/success/'; ?>">
            <div class="menuSub me">
                <div class="divMenuIcon me"></div>
                <div class="divMenuName me">Cá Nhân</div>
            </div>
        </a>
        <a>
            <div class="menuSub noti">
                <div class="divMenuIcon noti"></div>
                <div class="divMenuName noti">Chọc</div>
            </div>
        </a>

        <a href="<?php
        if($actionUserID == $actionLocationID)
            echo $this->url('success', array('action' => 'friend'));
        else
            echo $this->basePath().'/success/friend?user='. $actionLocationID;
        ?>">
            <div class="menuSub friend">
                <div class="divMenuIcon friend"></div>
                <?php
                if($getNotifFriend != null && $getNotifFriend > 0)
                {
                ?>
                <div class="divMenuName friend" id="menuFriend" data-notifications="<?php echo $getNotifFriend;?>">Bạn bè</div>

                <?php
                }
                else
                {
                ?>
                    <div class="divMenuName friend" id="menuFriend" >Bạn bè</div>
                <?php
                }
                ?>
                <div class="arrow_box" style=" position: relative; display: none;">
                    <div>
                        <img src="">
                    </div>
                </div>
            </div>
        </a>

        <?php if($actionUserID == $actionLocationID) { ?>

        <a>
            <div class="menuSub mail">
                <div class="divMenuIcon mail"></div>
                <div class="divMenuName mail">Hộp thư</div>
            </div>
            </a>
        <a href="<?php echo $this->url('success', array('action' => 'update-info')); ?>">
            <div class="menuSub config">
                <div class="divMenuIcon config"></div>
                <div class="divMenuName config">Cài đặt</div>
            </div>
        </a>

        <?php } ?>
    </div>

    <div class="divUserPanel">
        <div class="userAvatar">
            <img src="<?php echo $this->basePath().'/uploads/'.$bigAvatar; ?>" id="userAvatar" />
        </div>
        <div class="userInfo">
            <div class="info name" id="avai-userid" name="<?php echo $actionUserID; ?>">
                <?php echo $datauser->getLastname() .' '. $datauser->getFirstname(); ?>
            </div>
            <div style="display: none" id="actionLocation" name="<?php echo $actionLocationID; ?>"></div>
            <div class="info age">
                <div class="infoIcon age"></div>
                <div class="infoContent age">
                    <?php
                        if($datauser->getDOB() != null)
                        {
                            $date = new DateTime($datauser->getDOB());
                            echo date_format($date, 'd-m-Y');
                        }
                        else
                        {
                            echo "Chưa cập nhật.";
                        }
                    ?>
                </div>
            </div>
            <div class="info address">
                <div class="infoIcon address"></div>
                <div class="infoContent address">
                    <?php
                        if($datauser->getAddress() != null)
                        {
                            echo $datauser->getAddress();
                        }
                        else
                        {
                            echo "Chưa cập nhât.";
                        }
                    ?>
                </div>
            </div>
            <div class="info quote">
                <div class="infoIcon quote"></div>
                <div class="infoContent quote">
                    <?php
                        if($datauser->getQuote() != null)
                        {
                            echo $datauser->getQuote();
                        }
                        else
                        {
                            echo "Chưa cập nhật";
                        }
                    ?>
                </div>
                <?php

//                var_dump($checkFriend);die();
                if($checkFriend == "HOME")
                {
                }
                elseif($checkFriend == "ACCEPTED")
                {
                ?>
                    <span style="display: block; margin-top: 40px; margin-left: 22px; font-size: 14px">Hủy kết bạn</span>
                    <a href="#" style="margin-top:12px; " class="a-btn" id="unFriend">
						<span class="a-btn-text">+</span>
						<span class="a-btn-slide-text">Hủy</span>
						<span class="a-btn-icon-right"><span></span></span>
					</a>

                <?php
                }
                else
                {
                ?>
                    <a href="#" style="margin-top:30px; " class="a-btn" id="addFriend">
                        <span class="a-btn-text">+</span>
                        <span class="a-btn-slide-text">
                            <?php
                            if($checkFriend == "SENT")
                            {
                                echo "Đã gửi";
                            }
                            elseif($checkFriend == "WAITTING")
                            {
                                echo "Đang chờ";
                            }
                            else
                                echo "Kết bạn";
                            ?>
                        </span>
                        <span class="a-btn-icon-right"><span></span></span>
                    </a>
                <?php
                }

                ?>
                </div>
            <div class="logOut">
                <div class="infoIcon logout"></div>
                <a href="<?php echo $this->url('success', array('action' => 'logout')); ?>" style="color: white;"><div class="infoContent logout">Log Out</div></a>
            </div>
        </div>
    </div>
</div>


<div class="divRight">
    <div class="divCover">
        <img id="imgCover" src="<?php echo $this->basePath().'/uploads/'.$imageCover; ?>" />
    </div>
    <?php
    if($checkFriend == "ACCEPTED" or $checkFriend =="HOME")
    {


    ?>

    <div class="statusBlock">
        <div class="statusType">
            <div id="clickStatus" style="cursor: pointer;" class="type normal">Trạng thái</div>
            <div id="clickShare" class="type share">Chia sẻ</div>

            <?php
            if($checkFriend == "HOME")
            {
            ?>
            <div id="clickImage" class="type image">Đăng Ảnh</div>
            <div id="clickVideo" class="type video">Đăng Video</div>

            <?php
            }
            ?>

        </div>
        <div class="statusContent">

            <div class="clickStatus" style="display: block;">
                <form action="" method="post" id="formSubStatus">
                    <div class="statusComposeArea">
                        <textarea name="contentStatus" id="statusPostContent" placeholder="Nhập vào trạng thái của bạn... "></textarea>
                    </div>
                    <div class="btnSubmit">
                        <input id="btnPost" class="postStatus" type="submit" value="Đăng" />
                    </div>
                </form>
            </div>

            <div class="clickShare" style="display: none;">
                <form method="post" id="form-postShare"  enctype="multipart/form-data">
                    <div class="statusComposeArea">
                        <div class="place-image">
                            <input class="hide-btn" type="button">
                            <input type="file" id="btnLoadShare" name="image" accept="image/*"/>
                        </div>
                        <div class="place-name">
                            <input type="text" class="txt-place-name" name="placeName" id="placeName" placeholder="Tên địa điểm bạn muốn chia sẻ...">
                        </div>
                        <div class="place-description">
                            <textarea id="descriptPlace" name="descriptPlace" class="txt-place-des" placeholder="Bạn hãy mô tả về địa điểm của mình ..."></textarea>
                        </div>

                    </div>
                    <div class="btnSubmit">
                        <input id="btnPost" class="postShare" type="submit" value="Đăng" />
                    </div>
                </form>
            </div>

            <div class="clickImage" style="display: none;">
                <form method="post" action=""
                      id="form-postImage" name="form-postImage" enctype="multipart/form-data">
                    <div class="statusComposeArea">
                        <input type="text" class="descriptImage" name="descriptImage" placeholder="Nhập bình luận của bạn về ảnh này..."/>
                        <input type="file" class="btnLoadImage" id="btnLoadImage" name="image" accept="image/*"/>
                    </div>
                    <div class="btnSubmit">
                        <input id="btnPost" class="postImage" type="submit" value="Đăng Ảnh" />
                    </div>
                </form>
            </div>

            <div class="clickVideo" style="display: none;">
                <form method="post" action="" id="form-postVideo" name="form-postVideo" enctype="multipart/form-data">
                    <div class="statusComposeArea">
                        <input type="text" class="descriptVideo" name="descriptVideo" placeholder="Nhập bình luận của bạn về video này..." />
                        <input type="file" class="btnLoadVideo" id="btnLoadVideo" name="video" accept="video/*" />

                    </div>
                    <div class="btnSubmit">
                        <input id="btnPost" class="postVideo" type="submit" value="Đăng Video" />
                    </div>
                </form>
            </div>
        </div>
    </div>

    <?php
    }
    ?>

<!--  moi them vao  -->
<!--    <div class="scroll-now" style="overflow: scroll; height: 800px; width: 100%;">-->
    <?php
    function getFullTime($date)
    {
        $value  = ' lúc '.date('H', $date). ' giờ ';
        $value .= date('i', $date) . ' phút';
        $value .= ' ngày '.date('d/m/Y', $date);
        return $value;
    }
    arsort($arrayTrueActionID);
    foreach($arrayTrueActionID as $actionID)
    {
        $isOnAnotherWall = false;
        $checkUser  =  $arrayActuserAclocation[$actionID]['actionUser'];
        $checkLocation  =  $arrayActuserAclocation[$actionID]['actionLocation'];
        if($checkUser != $checkLocation)
        {
            $isOnAnotherWall = true;
        }

//        var_dump($arrayActuserAclocation); die();
    ?>
    <div class="divAction">
        <div class="divStatus">
            <div class="statusAvatar">
                <img src="
                <?php
                    echo $this->basePath().'/uploads/'. $infoUseronWal[$checkUser]['pathAvatar'];
                ?>
                " />
            </div>
            <div class="statusRightPanel">
                <div class="statusPosition">
                    <span>
                        <?php
                        echo $infoUseronWal[$checkUser]['fullname'];
                        ?>
                    </span> &curren;
                    <?php
                    echo getFullTime($arrayActionCreatedTime[$actionID]);
                    ?>
                </div>
                <div class="statusContent">
                    <?php
//                    var_dump($arrayActionType); die();
                    $statusID = $arrayActionType[$actionID];

                    if(substr($statusID,0,3) == "STT")
                    {
                        echo "<pre>".$arrayStatusContent[$statusID]."</pre>";
                    }
                    elseif(substr($statusID,0,3) == "IMG")
                    {
//                        var_dump($arrayPathALLIMAGE) ; die();
                        echo "<pre>".$arrayPathALLIMAGE[$statusID]['content']."</pre>";
                        echo "<img src='".$this->basePath()."/uploads/". $arrayPathALLIMAGE[$statusID]['path']."'/>";
                    }
                    elseif(substr($statusID,0,3) == "VID")
                    {
                        echo "<pre>".$arrayPathALLVIDEO[$statusID]['content']."</pre>";
                        $pathViddeo = $arrayPathALLVIDEO[$statusID]['path'];
                        $typteVideo = substr($pathViddeo, -3, 3);

                    ?>

                    <video id="example_video_1" class="video-js vjs-default-skin" controls preload="true" width="100%" height="375"
                           poster=""
                           data-setup="{}">

<!--                        --><?php //echo $this->basePath().'/img/Logo_Video.png'; ?>
                        <source src="<?php echo $this->basePath().'/uploads/'.$pathViddeo;?>"
                                type='video/<?php echo $typteVideo ?>'>
                    </video>

                    <?php

                    }
                    else{

                    ?>

                        <div class="statusContent">
                        <div class="status-place-image">
                            <img src="<?php echo $this->basePath().'/uploads/'.$arrayALLSharePlace[$statusID]['pathImage']?>">
                        </div>
                        <div class="status-place-name">
                            <span class="name"><?php echo $arrayALLSharePlace[$statusID]['placeName']; ?></span><br>
                            <span class="hashtag"><?php echo $arrayALLSharePlace[$statusID]['hashTag']; ?></span>
                        </div>
                        <div class="status-place-des">
                            <pre><?php echo $arrayALLSharePlace[$statusID]['placeDescription']; ?></pre>
                        </div>
                    </div>

                    <?php
                    }

                    ?>
                </div>
                <div class="statusFooter">
                    <div class="summary" >
                        <?php

//                        var_dump($checkLikeYourself);die();

                        $checkStatusLike = "like";
                        if(isset($checkLikeYourself[$actionID]))
                        {
                            foreach($checkLikeYourself[$actionID] as $value)
                            {
                                    if($value['userLiked'] == $actionUserID)
                                    $checkStatusLike = "unlike";
                            }
                        }
//                        var_dump($checkStatusLike);die();

                        ?>

                        <a class="<?php  echo $checkStatusLike; ?>" name="<?php echo $actionID; ?>"
                           id="<?php if($checkStatusLike=="unlike") echo $checkLikeYourself[$actionID][$actionUserID]['actOfLike'] ?>" style="cursor: pointer;" >
                        <?php
//                        var_dump($checkLikeYourself);die();

                       if($checkStatusLike == "like")
                            echo "Thích";
                        else
                            echo "Bỏ thích";

                        ?>
                        </a>
                        <a class="comment" href="javascript:void(0)">Bình luận</a>
                        <a class="share" href="javascript:void(0)">Chia sẻ</a>
                    </div>
                    <div class="icon">
                        <a class="like" href="javascript:void(0)"></a>
                        <span class="like-span<?php echo $actionID;?>">
                            <?php
                            if(isset($countLikes[$actionID]))
                                echo $countLikes[$actionID];
                            else
                                echo 0;
                            ?></span>
                        <a class="comment" href="javascript:void(0)"></a><span class="commemt">0</span>
                        <a class="share" href="javascript:void(0)"></a><span class="share">0</span>
                    </div>
                </div>
                <div class="divComment" >
                <?php
                $names = $allCommentID;

                usort($allCommentID, function($a, $b) {
                    $a = substr($a, -10, 10);
                    $b = substr($b, -10, 10);
                    return strcmp($a, $b);
                });

//                var_dump($allCommentID);die();

                foreach($allCommentID as $comentid)
                {

                    if(isset($arrayCommentContent[$actionID][$comentid]))
                    {
//                        var_dump($actionIDofCMT);die();

                ?>
                    <div class="commentAction">
                        <div class="commentUserAvatar">
                            <img src="<?php echo $this->basePath().'/uploads/'.$infoUserCommented[$comentid]['pathAvatar'].'"' ?>">
                        </div>
                        <div class="commentRight">
                            <div class="commentContent"><div class="commentUserName">
                                    <?php echo $infoUserCommented[$comentid]['fullname']; ?>
                                </div>
                                <?php
                                    echo $arrayCommentContent[$actionID][$comentid];
                                ?>
                            </div>
                            <div class="commentFooter">
                                <div class="commentLike">
                                    <?php
                                    $checResult = "like";
//                                    var_dump($commentid);die();
                                    if(isset($checkLikeYourself[$actionIDofCMT[$comentid]]))
                                    {

                                        $actionIDForCMT = $actionIDofCMT[$comentid];
                                        foreach($checkLikeYourself[$actionIDForCMT] as $node)
                                        {
                                            if($node['userLiked'] == $actionUserID)
                                                $checResult =  "unlike";
                                        }
                                    }
                                    ?>

                                    <a class="<?php echo $checResult;?>"
                                       style="cursor: pointer;" name="<?php echo $actionIDofCMT[$comentid]; ?>"
                                       id="<?php if($checResult == "unlike") echo $checkLikeYourself[$actionIDofCMT[$comentid]][$actionUserID]['actOfLike'] ?>">
                                        <?php
                                       if($checResult == "like")
                                            echo "Thích";
                                        else
                                            echo "Bỏ thích";
                                        ?>
                                    </a>
                                    <a href="#" class="number">
                                        <?php
                                        if(isset($countLikes[$actionIDofCMT[$comentid]]))
                                            echo $countLikes[$actionIDofCMT[$comentid]];
                                        else
                                            echo 0;
                                        ?>
                                    </a>
                                </div>
                                <div class="commentTime" title="<?php
                                $dateComment =  substr($comentid, -10,10);
                                echo getFullTime($dateComment);

                                ?>">
                                <?php
                                    echo time_difference($dateComment);
                                ?>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php
                    }
                }

                if($checkFriend == "ACCEPTED" or $checkFriend == "HOME")
                {
                ?>
                    <div class="commentCompose" id="placeNewCMT_<?php echo $actionID; ?>">
                        <div class="commentUserAvatar">
                            <img src="<?php echo $this->basePath().'/uploads/'. $smallAvatar;  ?>"/>
                        </div>
                        <form class="form-subPostCmt" name="<?php echo $actionID; ?>" id="fCmt<?php echo $actionID; ?>">
                            <div class="commentRight">
                                <textarea name="cmtContentArea" class="contentPostComment"></textarea>
                            </div>
                            <input type="submit" class="postComment" value="Đăng" />
                        </form>
                    </div>
                    <?php
                }
                    ?>
                </div>
            </div>
        </div>
    </div>

    <?php

        }
    ?>
        <!--   moi them vao     -->
<!--        </div>-->

</div>

<script type="text/javascript">
    function getTimestampNow()
    {
        var datenow = new Date();
        datenow = parseInt(datenow.setFullYear(datenow.getFullYear(), datenow.getMonth(), datenow.getDate())/1000);
        return datenow;
    }
</script>

<script type="text/javascript">
    jQuery(document).ready(function(){

        var oldDiv =jQuery('.clickStatus');

        jQuery('.statusType div').each(function(){
            jQuery(this).click(function(){
                var newDiv = jQuery(this).attr('id');
                newDiv = jQuery('.'+newDiv);
                var t = 500;
                if(newDiv.text() != oldDiv.text())
                {
                    oldDiv.slideUp(1000, 'easeInBounce');
                    newDiv.slideDown(1000, 'easeOutBounce');
                    oldDiv = newDiv;
                }
            });
        });

        jQuery('.form-subPostCmt input.postComment').each(function(){
            jQuery(this).on('click',function(){
                var form = jQuery(this).parent().attr('id');
                var actionIDforCMT = jQuery(this).parent().attr('name');
                var objForm = "#" + form;
//                var actionIDforCMT = jQuery(objForm).attr('name');

                var textAreaComment = jQuery('form#'+form + ' textarea.contentPostComment');
                var valueComment = textAreaComment.val();
//                alert(actionIDforCMT);
//                alert(valueComment);
                checkFormCommentArea(jQuery(objForm), valueComment, actionIDforCMT);
//                textAreaComment.val('');
            });
        });

        function checkFormCommentArea(form, cmtContent, actionIDforCMT)
        {
//            alert('da vao day');
            form.validate({
                errorElement: "p",
                rules: {
                    cmtContentArea : {
                        required:true
                    }
                },
                messages:{
                    cmtContentArea:{
                        required: '*Nhập bình luận của bạn vào đây.'
                    }
                },
                submitHandler : function(){

                    ajaxsaveCommentfromAction(cmtContent,form, actionIDforCMT);
                }
            });
        }

        function ajaxsaveCommentfromAction(cmtContent, form, actionIDforCMT)
        {
            //timestamp là lúc colick vào postComment
            var timeNow = getTimestampNow();
            var actionUser = jQuery('#avai-userid').attr('name');
            var actionLocation = jQuery('#actionLocation').attr('name');
            var data = "actionUser=" +actionUser+"&actionLocation="+actionLocation+"&cmtContent="+ cmtContent +"&timeCreatedComment="+timeNow + "&actionStatusSave="+actionIDforCMT;
//            alert(data);
            jQuery.ajax({
                type: "POST",
                url: "<?php echo $this->url('success', array('action' => 'savecomment')); ?>",
                data: data,
                async:false,
                success: function(data) {
//                    alert(data);
                    data = JSON.parse(data);
                    var success = data['success'];
                    if(success == "1")
                    {
//                        @TODO:
                        instanceShowComment(cmtContent, timeNow, form);
                        form[0].reset();
                    }
                    else
                    {
                        alert('Đăng bình luận thất bại. Hãy thử lại sau một ít phút nữa.');

                    }
                },
                error: function() {
                    alert("Hệ thống đang bảo trì, xin hãy thử lại sau một ít phút nữa!");
                }
            });
//            return false;
        }

        function instanceShowComment(commentContent, timestamp, form)
        {
            var time = " vài giây trước ";

            var divCommentAction = document.createElement('div');
            divCommentAction.className = "commentAction";

            var divCommentUserAvatar = document.createElement('div');
            divCommentUserAvatar.className = "commentUserAvatar";

            var imgCommentUserAvatar = document.createElement('img');
            jQuery(imgCommentUserAvatar).attr('src', '<?php echo $this->basePath()."/uploads/". $smallAvatar;?>');

            var divCommentRight = document.createElement('div');
            divCommentRight.className='commentRight';

            var divcommentContent = document.createElement('div');
            divcommentContent.className='commentContent';

            var divcommentUserName = document.createElement('div');
            divcommentUserName.className='commentUserName';
            jQuery(divcommentUserName).text('<?php  echo $dataGuest->getLastname() .' '. $dataGuest->getFirstname(); ?>');
            jQuery(divcommentContent).append(commentContent);

            var divcommentFooter = document.createElement('div');
            divcommentFooter.className='commentFooter';

            var divcommentLike = document.createElement('div');
            divcommentLike.className='commentLike';

            var tagaLike = document.createElement('a');
            tagaLike.className='like';
            jQuery(tagaLike).text('Thích');
            jQuery(tagaLike).css('cursor', 'pointer');
            jQuery(tagaLike).attr('name', 'ACT'+timestamp);


            var tagaCountLike = document.createElement('a');
            tagaCountLike.className="number";
            jQuery(tagaCountLike).text('0');

            var divcommentTime = document.createElement('div');
            divcommentTime.className='commentTime';
            jQuery(divcommentTime).text(time);

            divCommentAction.appendChild(divCommentUserAvatar);
                divCommentUserAvatar.appendChild(imgCommentUserAvatar);

            divCommentAction.appendChild(divCommentRight);
                divCommentRight.appendChild(divcommentContent);
                    divcommentContent.appendChild(divcommentUserName);
                divCommentRight.appendChild(divcommentFooter);
                    divcommentFooter.appendChild(divcommentLike);
                        divcommentLike.appendChild(tagaLike);
                        divcommentLike.appendChild(tagaCountLike);
                    divcommentFooter.appendChild(divcommentTime);


            var actID = form.attr('name');
//            jQuery(form.parent().attr('id')).before(divCommentAction);
            var buttonLikeCMT =  jQuery(tagaLike);
            buttonLikeCMT.click(function(){
                var actionID = buttonLikeCMT.attr('name');
                var actionUser = jQuery('#avai-userid').attr('name');
                var actionLocation = jQuery('#actionLocation').attr('name');
                var timeStamp = getTimestampNow();
                var checkUnlikeLike = buttonLikeCMT.attr('class');

//                alert(checkUnlikeLike);

                if(checkUnlikeLike == "like"){
                    buttonLikeCMT.attr('class', 'unlike');
                    var likeID = 'LIK'+actionLocation+timeStamp;
                    buttonLikeCMT.attr('id', likeID);
                    setLikeStatus(actionID, timeStamp, actionUser, actionLocation, buttonLikeCMT);
                    var divCMTLike = buttonLikeCMT.next();

//                    var countLike = jQuery('.'+divCMTLike+'> a.number');
                    var newCount = divCMTLike.text();
                    newCount = parseInt(newCount) + 1;
                    divCMTLike.html(newCount);
                }
                else{
                    var likeID = buttonLikeCMT.attr('id');
                    buttonLikeCMT.attr('class', 'like');
                    buttonLikeCMT.attr('id', '');
                    setUnlikeStatus(likeID, buttonLikeCMT);
                    var divCMTLike = buttonLikeCMT.next();
                    var newCount = divCMTLike.text();
                    newCount = parseInt(newCount) - 1;
                    divCMTLike.html(newCount);
                }
            });

            var hung = jQuery("#placeNewCMT_" + actID);
//
//            alert(hung.attr('class'));
//
            hung.before(divCommentAction);
        }

        //phan post comment

        jQuery('.postStatus').click(function(){
            checkFormpostStatus();
        });


        function ajaxSubtmitPostStatus()
        {
            var status = jQuery('#statusPostContent').val();
            var timeNow = getTimestampNow();
            var actionLocation = jQuery('#actionLocation').attr('name');
            var actionUser = jQuery('#avai-userid').attr('name');


            var data = "status="+status+"&timestamp="+timeNow + "&actionUser=" +actionUser+"&actionLocation=" +actionLocation;
//            alert(data);

            jQuery.ajax({
                type: "POST",
                url: "<?php echo $this->url('success', array('action' => 'savestatus')); ?>",
                data: data,
                async:false,
                success: function(data) {
//                    alert(data);
                    data = JSON.parse(data);
                    var success = data['success'];
                    var divError = jQuery('#statusPostContent span');
                    if(success == "1")
                    {
                        divError.html(data['message']);
                        divError.show().delay(4000).fadeOut();

                        instancePostStatus(status, timeNow);
                        jQuery('#statusPostContent').val('');
                        var divFirstAction =  jQuery('.statusBlock').next();
                        divFirstAction.css("opacity", 0);
                        divFirstAction.animate({
                            opacity:1
                        },3000, "linear");
                    }
                    else
                    {
//                        alert('that bai');
                        divError.html(data['error']);
                        divError.fadeIn(600).delay(4000).fadeOut();
                    }
                },
                error: function() {
                    alert("Hệ thống đang bảo trì, xin hãy thử lại sau một ít phút nữa!");
                }
            });
            return false;
        }

        function checkFormpostStatus()
        {
            jQuery('#formSubStatus').validate({
                errorElement: "span",
                rules: {
                    contentStatus : {
                        required:true
                    }
                },
                messages:{
                    contentStatus:{
                        required: "*.Cảm xúc của bạn là trống rỗng ?"
                    }
                },
                submitHandler : function(){
                    ajaxSubtmitPostStatus();
                }
            });
        }

        function instancePostStatus(statusContent, timeStamp)
        {
            var showdate = new Date();
            var hour = showdate.getHours();
            var minute = showdate.getMinutes();
            var date = showdate.getDate();
            var month = showdate.getMonth();
            var year = showdate.getFullYear();

            showdate = ' lúc '+hour+' giờ '+minute+' phút ngày '+date+'/'+month+'/'+year;

            var divAction = document.createElement('div');
            divAction.className = 'divAction';

            var divStatus = document.createElement('div');
            divStatus.className='divStatus';

            var divStatusAvatar = document.createElement('div');
            divStatusAvatar.className='statusAvatar';

            var imgDivStatusAvatar = document.createElement('img');
            var actionName = 'ACT'+timeStamp;
            imgDivStatusAvatar.src="<?php echo $this->basePath().'/uploads/'.$smallAvatar; ?>";

            var divStatusRightPanel = document.createElement('div');
            divStatusRightPanel.className='statusRightPanel';

            var divstatusPosition = document.createElement('div');
            divstatusPosition.className='statusPosition';

            var spandivstatusPosition = document.createElement('span');
            spandivstatusPosition.innerHTML='<?php echo $dataGuest->getLastname() .' '. $dataGuest->getFirstname(); ?>';
            jQuery(spandivstatusPosition).append("<p style='display: inline-block;color: #333; font-size: 12px;'>&curren; "+showdate+"</p>");

            var divstatusContent = document.createElement('div');
            divstatusContent.className= 'statusContent';
//            jQuery(divstatusContent).innerHTML=statusContent;
            jQuery(divstatusContent).append('<pre>' + statusContent + '</pre>');

            var divstatusFooter = document.createElement('div');
            divstatusFooter.className='statusFooter';

            var divsummary = document.createElement('div');
            divsummary.className='summary';

            var tagaLike = document.createElement('a');
            tagaLike.className='like';
            tagaLike.innerHTML='Thích';
            jQuery(tagaLike).css('cursor', 'pointer');
            jQuery(tagaLike).attr('name', 'ACT'+timeStamp );
            jQuery(tagaLike).attr('id', '');

            var tagsComment = document.createElement('a');
            tagsComment.className='comment';
            tagsComment.innerHTML='Bình luận';

            var tagaShare = document.createElement('a');
            tagaShare.className='share';
            tagaShare.innerHTML='Chia sẻ';

            var divIcon = document.createElement('div');
            divIcon.className='icon';

            var tagaLikeCount = document.createElement('a');
            tagaLikeCount.className='like';
            jQuery(tagaLikeCount).css('cursor', 'pointer');

            var spanLikeCount = document.createElement('span');
            spanLikeCount.className='like-spanACT'+timeStamp;
            jQuery(spanLikeCount).text('0');

            var tagaCommentCount = document.createElement('a');
            tagaCommentCount.className='comment';
            jQuery(tagaCommentCount).attr('href', 'javascript:void(0)');

            var spanCommentCount = document.createElement('span');
            spanCommentCount.className='comment';
            jQuery(spanCommentCount).text('0');

            var tagaShareCount = document.createElement('a');
            tagaShareCount.className = 'share';
            jQuery(tagaShareCount).attr('href', 'javascript:void(0)');

            var spanShareCount = document.createElement('span');
            spanShareCount.className = 'share';
            jQuery(spanShareCount).text('0');

            var divComment = document.createElement('div');
            divComment.className='divComment';

            var divcommentCompose = document.createElement('div');
            divcommentCompose.className='commentCompose';
            jQuery(divcommentCompose).attr('id', 'placeNewCMT_ACT'+timeStamp);

            var divcommentUserAvatar = document.createElement('div');
            divcommentUserAvatar.className='commentUserAvatar';

            var imgcommentUserAvatar = document.createElement('img');
            imgcommentUserAvatar.src='<?php echo $this->basePath().'/uploads/'. $smallAvatar;?>';

            var formSubtmit = document.createElement('form');
            formSubtmit.className='form-subPostCmt';
            formSubtmit.id='fCmtACT' + timeStamp;
            jQuery(formSubtmit).attr('name','ACT'+timeStamp );

            var divcommentRight = document.createElement('div');
            divcommentRight.className='commentRight';

            var textareaComment = document.createElement('textarea');
            textareaComment.className='contentPostComment';
            jQuery(textareaComment).attr('name', 'cmtContentArea');

            var postComment = document.createElement('input');
            postComment.className = 'postComment';
            jQuery(postComment).attr('type', 'submit');
            jQuery(postComment).attr('value', 'Đăng');

            divAction.appendChild(divStatus);
                divStatus.appendChild(divStatusAvatar);
                    divStatusAvatar.appendChild(imgDivStatusAvatar);
                divStatus.appendChild(divStatusRightPanel);
                    divStatusRightPanel.appendChild(divstatusPosition);
                        divstatusPosition.appendChild(spandivstatusPosition);
                    divStatusRightPanel.appendChild(divstatusContent);
                    divStatusRightPanel.appendChild(divstatusFooter);
                        divstatusFooter.appendChild(divsummary);
                            divsummary.appendChild(tagaLike);
                            divsummary.appendChild(tagsComment);
                            divsummary.appendChild(tagaShare);
                        divstatusFooter.appendChild(divIcon);
                            divIcon.appendChild(tagaLikeCount);
                            divIcon.appendChild(spanLikeCount);
                            divIcon.appendChild(tagaCommentCount);
                            divIcon.appendChild(spanCommentCount);
                            divIcon.appendChild(tagaShareCount);
                            divIcon.appendChild(spanShareCount);

            divStatusRightPanel.appendChild(divComment);
            divComment.appendChild(divcommentCompose);
            divcommentCompose.appendChild(divcommentUserAvatar);
                divcommentUserAvatar.appendChild(imgcommentUserAvatar);
            divcommentCompose.appendChild(formSubtmit);
            formSubtmit.appendChild(divcommentRight);
            divcommentRight.appendChild(textareaComment);
            formSubtmit.appendChild(postComment);

            jQuery(postComment).on('click', function(){

                var value = jQuery(textareaComment).val();
                checkFormCommentArea(jQuery(formSubtmit), value,'ACT'+ timeStamp);
            });

            var buttonLike = jQuery(tagaLike);
            buttonLike.on('click', function(){
                var actionid = buttonLike.attr('name');
                var timeStamp = getTimestampNow();
                var actionUser = jQuery('#avai-userid').attr('name');
                var actionLocation = jQuery('#actionLocation').attr('name');

                var checkLikeUnlike = buttonLike.attr('class');

                if(checkLikeUnlike == "like")
                {
                    buttonLike.attr('class', 'unlike');
                    var like = 'LIK'+actionLocation+timeStamp;
                    buttonLike.attr('id',like );
                    setLikeStatus(actionid, timeStamp, actionUser, actionLocation, buttonLike);
                    var likeRightNow = jQuery('.like-span' + actionid);
                    var changeLike = parseInt(likeRightNow.text()) + 1;
//                    alert(changeLike);
                    jQuery(likeRightNow).html(changeLike);

                }
                else
                {
                    buttonLike.attr('class', 'like');
                    var likeID = buttonLike.attr('id');
                    buttonLike.attr('id', '');
                    setUnlikeStatus(likeID, buttonLike);
                    var likeRightNow = jQuery('.like-span' + actionid);
                    var changeLike = parseInt(likeRightNow.text()) - 1;
//                    alert(changeLike);
                    jQuery(likeRightNow).html(changeLike);
                }

            });

            jQuery('.statusBlock').after(divAction);
        }

        jQuery('.postImage').click(function(){
            checkFormPostImage();
        });

        jQuery.validator.addMethod('accept', function () { return true; });

        function checkFormPostImage()
        {
            jQuery('#form-postImage').validate({
                debug: true,
                errorElement: "p",
                rules: {
                    image:{
                        required:true,
                        accept: "image/pjpeg,image/jpeg,image/png,image/gif"
                    }
                },
                messages:{
                    image:{
                        required:"Bạn chưa chọn hình để tải lên!",
                        accept: "jpg|jpeg|png|gif"
                    }
                },
                submitHandler : function(){
                    ajaxUploadImageFromMenu();
                }
            });
        }

        function ajaxUploadImageFromMenu()
        {

            var timeNow = getTimestampNow();
            var descript = jQuery('.descriptImage').val();
            var formdata  = new FormData(jQuery('#form-postImage')[0]);
            var reader = new FileReader();
            var value = reader.readAsDataURL(document.getElementById("btnLoadImage").files[0]);
            var userid = jQuery('#avai-userid').attr('name');

            formdata.append('image', value);
            formdata.append('timestamp', timeNow);
            formdata.append('descript', descript);
            formdata.append('actionUser', userid);

//            var data = "descript="+ descript +"&actionID="+actionID+"&timestamp="+ timeNow;

            jQuery.ajax({
                type: "POST",
                url: "<?php echo $this->basePath().'/plugin/upload_normal.php' ;?>",
                data: formdata,
                cache: false,
                contentType: false,
                processData: false,
                async:false,
                success: function(data) {
                    if(data!='error')
                    {
                        ajaxSaveImageNormal(userid, timeNow, descript, data);
                        jQuery('#form-postImage')[0].reset();
                    }
                },
                error: function() {
                    alert("Hệ thống đang bảo trì, xin hãy thử lại sau một ít phút nữa!");
                }
            });
            return false;
        }

        function ajaxSaveImageNormal(userid, timstamp, descript, data)
        {
            var dataval = "userid=" + userid+"&createdTime=" + timstamp+"&descript="+descript+"&imageType=" +data;
            jQuery.ajax({
                type: "POST",
                url: "<?php echo $this->url('success', array('action' => 'savenormalimage')); ?>",
                data: dataval,
                async:false,
                success: function(data) {
                    data = JSON.parse(data);
    //                    alert('Đăng ảnh thành công!.');
                    var instanceImage = descript + " <img src='<?php echo $this->basePath();?>" +"/uploads/"+ data["success"] + "'/>";
//                    alert(instanceImage);
                    instancePostStatus(instanceImage, timstamp);
                    var divFirstAction =  jQuery('.statusBlock').next();
                    divFirstAction.css("opacity", 0);
                    divFirstAction.animate({
                        opacity:1
                    },3000, "linear");
                },
                error: function() {
                    alert("Hệ thống đang bảo trì, xin hãy thử lại sau một ít phút nữa!");
                }
            });
            return false;
        }

        //upload video

        jQuery('.postVideo').click(function(){
            jQuery('#form-postVideo').validate({
                errorElement: "p",
                rules: {
                    video:{
                        required:true
                    }
                },
                messages:{
                    video:{
                        required:"Bạn chưa chọn Video để tải lên!"
                    }
                },
                submitHandler : function(){
//                    alert('ajjax thoi');
                    ajaxMoveVideo();
                }
            });
        });

        function ajaxMoveVideo()
        {
            var timeNow = getTimestampNow();
            var descript = jQuery('.descriptVideo').val();
            var formdata  = new FormData(jQuery('#form-postVideo')[0]);
            var reader = new FileReader();
            var value = reader.readAsDataURL(document.getElementById("btnLoadVideo").files[0]);
            var userid = jQuery('#avai-userid').attr('name');
//            alert(userid + descript+timeNow);

            formdata.append('image', value);
            formdata.append('timestamp', timeNow);
            formdata.append('descript', descript);
            formdata.append('userid', userid);

            jQuery.ajax({
                type: "POST",
                url: "<?php echo $this->basePath().'/plugin/upload_video.php' ;?>",
                data: formdata,
                cache: false,
                contentType: false,
                processData: false,
                async:false,
                success: function(data) {
//                    alert(data);
                    if(data!='error')
                    {
                        ajaxSaveVideo(userid, timeNow, descript, data);
                        jQuery('#form-postVideo')[0].reset();
                    }
                    else
                    {
                        alert('Video tải lên không đúng định dạng hoặc dung lượng quá lớn!.');
                    }
                },
                error: function() {
                    alert("Hệ thống đang bảo trì, xin hãy thử lại sau một ít phút nữa!");
                }
            });
            return false;
        }

        function ajaxSaveVideo(userid, timeStamp, descript, dataType)
        {
            var dataval = "userid=" + userid+"&createdTime=" + timeStamp+"&descript="+descript+"&videoType=" +dataType;

            jQuery.ajax({
                type: "POST",
                url: "<?php echo $this->url('success', array('action' => 'savevideo')); ?>",
                data: dataval,
                async:false,
                success: function(data) {
//                    alert(data);
                    data = JSON.parse(data);
                    if(data['success'] == 1)
                    {
                        var videoType = dataType.substr(-3,3);
                        var videoName = 'VID'+userid+timeStamp+'.'+videoType;
                        var instanceVideo = descript;
                        instanceVideo += ' <video id="example_video_1" class="video-js vjs-default-skin" controls preload="true" ';
                        instanceVideo += ' width="100%" height="375" poster="" data-setup="{}"> ';
                        instanceVideo += '  <source src="<?php echo $this->basePath();?>' + '/uploads/'+videoName+ '" ';
                        instanceVideo += ' type="video/'+ videoType+' ">';
                        instanceVideo += ' </video>';

//                        alert(instanceVideo);

                        instancePostStatus(instanceVideo, timeStamp);
                        var divFirstAction =  jQuery('.statusBlock').next();
                        divFirstAction.css("opacity", 0);
                        divFirstAction.animate({
                            opacity:1
                        },3000, "linear");
                    }
                },
                error: function() {
                    alert("Hệ thống đang bảo trì, xin hãy thử lại sau một ít phút nữa!");
                }
            });
            return false;
        }

        jQuery('.postShare').click(function(){
//            alert('da click');
            jQuery('#form-postShare').validate({
                errorElement: "span",
                rules: {
                    share:{
                        required:true
                    },
                    placeName: {
                        required:true
                    },
                    descriptPlace:{
                        required : true
                    }
                },
                messages:{
                    share:{
                        required:"**"
                    },
                    placeName: {
                        required:"**"
                    },
                    descriptPlace:{
                        required : "**"
                    }
                },
                submitHandler : function(){
//                    alert('ajjax thoi');
                    saveImageofShare();
                }
            });
        });

        function saveImageofShare()
        {
            var timeNow = getTimestampNow();
            var placeName = jQuery('#placeName').val();
            var descript = jQuery('#descriptPlace').val();
            var formdata  = new FormData(jQuery('#form-postShare')[0]);
            var reader = new FileReader();
            var value = reader.readAsDataURL(document.getElementById("btnLoadShare").files[0]);
            var actionUser = jQuery('#avai-userid').attr('name');
            var actionLocation = jQuery('#actionLocation').attr('name');
//            alert(userid + descript+timeNow);

            formdata.append('image', value);
            formdata.append('timestamp', timeNow);
            formdata.append('descript', descript);
            formdata.append('placeName', placeName);
            formdata.append('actionUser', actionUser);
            formdata.append('actionLocation', actionLocation);

            jQuery.ajax({
                type: "POST",
                url: "<?php echo $this->basePath().'/plugin/upload_normal.php' ;?>",
                data: formdata,
                cache: false,
                contentType: false,
                processData: false,
                async:false,
                success: function(data) {
//                    alert(data);
                    if(data!='error')
                    {
                        var pathImage = data;
//                        alert('thanh cong');
                        ajaxSaveNewSharePlace(actionUser, actionLocation, timeNow, placeName, descript, pathImage);
                        jQuery('#form-postShare')[0].reset();
                    }
                    else
                    {
                        alert('Ảnh chia sẻ tải lên không đúng định dạng hoặc dung lượng quá lớn!.');
                    }
                },
                error: function() {
                    alert("Hệ thống đang bảo trì, xin hãy thử lại sau một ít phút nữa!");
                }
            });
            return false;
        }

        function createHashTag(str)
        {
            str = str.toLowerCase();
            str = str.replace(/à|á|ạ|ả|ã|â|ầ|ấ|ậ|ẩ|ẫ|ă|ằ|ắ|ặ|ẳ|ẵ/g, "a");
            str = str.replace(/è|é|ẹ|ẻ|ẽ|ê|ề|ế|ệ|ể|ễ/g, "e");
            str = str.replace(/ì|í|ị|ỉ|ĩ/g, "i");
            str = str.replace(/ò|ó|ọ|ỏ|õ|ô|ồ|ố|ộ|ổ|ỗ|ơ|ờ|ớ|ợ|ở|ỡ/g, "o");
            str = str.replace(/ù|ú|ụ|ủ|ũ|ư|ừ|ứ|ự|ử|ữ/g, "u");
            str = str.replace(/ỳ|ý|ỵ|ỷ|ỹ/g, "y");
            str = str.replace(/đ/g, "d");
            str = str.replace(/!|\$|\@|%|\^|\*|\(|\)|\+|\=|\<|\>|\?|\/|,|\.|\:|\;|\'| |\"|\&|\#|\[|\]|~|$|-/g, "_");
            //thay doi toan bo cac ki tu la trong chuoi
            str = str.replace(/_+_/g, "_"); //thay the 2 dau __ thanh 1_
            str = str.replace(/^\_+|\_+$/g, ""); // bo ki tu dau va cuoi chuoi
            return '#' +str;
        }

//        alert(createHashTag('- _ Sông cầu _ !@#$%^&*()_+'));

        function ajaxSaveNewSharePlace(actionUser, actionLocation, timeNow, placeName, descript, pathImage)
        {

            var hashTag = createHashTag(placeName);
            var dataval = "actionUser=" + actionUser+ "&actionLocation="+actionLocation+"&createdTime=" + timeNow+"&placeName="+placeName;
            dataval += "&descript="+descript+"&imageType=" +pathImage + "&hashTag=" + hashTag;

//            alert(dataval);

            jQuery.ajax({
                type: "POST",
                url: "<?php echo $this->url('success', array('action' => 'saveshareplace')); ?>",
                data: dataval,
                async:false,
                success: function(data) {
//                    alert(data);
                    data = JSON.parse(data);
                    var instanceImage = " <img src='<?php echo $this->basePath();?>" +"/uploads/"+pathImage + "'/>";
                    instanceImage +=    "<div class='status-place-name'>";
                    instanceImage +=        "<span class='name'>"+placeName+"</span></br>";
                    instanceImage +=        "<span class='hashtag'>"+hashTag+"</span></br>";
                    instanceImage +=    "</div>";
                    instanceImage += "<div class='status-place-des'><pre>"+descript+"</pre></div>";
//                    alert(instanceImage);
                    instancePostStatus(instanceImage, timeNow);
                    var divFirstAction =  jQuery('.statusBlock').next();
                    divFirstAction.css("opacity", 0);
                    divFirstAction.animate({
                        opacity:1
                    },3000, "linear");
                },
                error: function() {
                    alert("Hệ thống đang bảo trì, xin hãy thử lại sau một ít phút nữa!");
                }
            });
            return false;
        }

        //FUNCTION FOR LIKE &SHARE
        //Like status image, video, share
        jQuery('div.summary > a').each(function(){
            var buttonLike = jQuery(this);
            buttonLike.click(function(){
                var actionid = buttonLike.attr('name');
                var timeStamp = getTimestampNow();
                var actionUser = jQuery('#avai-userid').attr('name');
                var actionLocation = jQuery('#actionLocation').attr('name');

                var checkLikeUnlike = buttonLike.attr('class');
//                    alert(checkLikeUnlike);
                if(checkLikeUnlike == "like")
                {
                    buttonLike.attr('class', 'unlike');
                    var like = 'LIK'+actionLocation+timeStamp;
                    buttonLike.attr('id',like );
                    setLikeStatus(actionid, timeStamp, actionUser, actionLocation, buttonLike);

                    var likeRightNow = jQuery('.like-span' + actionid);
                    var changeLike = parseInt(likeRightNow.text()) + 1;
//                    alert(changeLike);
                    jQuery(likeRightNow).html(changeLike);

                }
                else
                {
                    buttonLike.attr('class', 'like');
                    var likeID = buttonLike.attr('id');
                    buttonLike.attr('id', '');
                    setUnlikeStatus(likeID, buttonLike);
                    var likeRightNow = jQuery('.like-span' + actionid);
                    var changeLike = parseInt(likeRightNow.text()) - 1;
//                    alert(changeLike);
                    jQuery(likeRightNow).html(changeLike);

                }
            });
        });

        function setLikeStatus(actionid, timeStamp, actionUser, actionLocation, buttonLike)
        {
            var data = "actionid="+ actionid +"&timeStamp="+timeStamp + "&actionUser="+actionUser + "&actionLocation=" +actionLocation;
//            alert('chua bi saveLikeStatus'+data);
            jQuery.ajax({
                type: "POST",
                url: "<?php echo $this->url('success', array('action' => 'savelikestatus')); ?>",
                data: data,
                async:false,
                success: function(data) {
//                    alert(data);
                    data = JSON.parse(data);
                    var success = data['success'];
                    if(success == "1")
                    {
                        buttonLike.text('Bỏ thích');
                    }
                    else
                    {
                        alert('Thích thất bại. Hãy thử lại sau một ít phút nữa.');
                    }
                },
                error: function() {
                    alert("Hệ thống đang bảo trì, xin hãy thử lại sau một ít phút nữa!");
                }
            });
            return false;
        }

        function setUnlikeStatus(likeID, buttonLike)
        {
            var data = "likeID=" + likeID;
//            alert('chuan bị unlike'+data);
            jQuery.ajax({
                type: "POST",
                url: "<?php echo $this->url('success', array('action' => 'unlikestatus')); ?>",
                data: data,
                async:false,
                success: function(data) {
//                    alert(data);
                    data = JSON.parse(data);
                    var success = data['success'];
                    if(success == "1")
                    {
                        buttonLike.text('Thích');
                    }
                    else
                    {
                        alert('Bỏ thích thất bại. Hãy thử lại sau một ít phút nữa');
                    }
                },
                error: function() {
                    alert("Hệ thống đang bảo trì, xin hãy thử lại sau một ít phút nữa!");
                }
            });
            return false;
        }

        //like comment cua status image video share
        jQuery('div.commentLike > a').each(function(){
//            alert(jQuery(this).attr('class'));
            var buttonLikeCMT = jQuery(this);



            buttonLikeCMT.click(function(){
                var actionID = buttonLikeCMT.attr('name');
                var actionUser = jQuery('#avai-userid').attr('name');
                var actionLocation = jQuery('#actionLocation').attr('name');
                var timeStamp = getTimestampNow();
                var checkUnlikeLike = buttonLikeCMT.attr('class');

//                alert(checkUnlikeLike);

                if(checkUnlikeLike == "like"){
                    buttonLikeCMT.attr('class', 'unlike');
                    var likeID = 'LIK'+actionLocation+timeStamp;
                    buttonLikeCMT.attr('id', likeID);
                    setLikeStatus(actionID, timeStamp, actionUser, actionLocation, buttonLikeCMT);
                    var divCMTLike = buttonLikeCMT.next();

//                    var countLike = jQuery('.'+divCMTLike+'> a.number');
                    var newCount = divCMTLike.text();
                    newCount = parseInt(newCount) + 1;
                    divCMTLike.html(newCount);
                }
                else{
                    var likeID = buttonLikeCMT.attr('id');
                    buttonLikeCMT.attr('class', 'like');
                    buttonLikeCMT.attr('id', '');
                    setUnlikeStatus(likeID, buttonLikeCMT);
                    var divCMTLike = buttonLikeCMT.next();
                    var newCount = divCMTLike.text();
                    newCount = parseInt(newCount) - 1;
                    divCMTLike.html(newCount);
                }
            });
        });


        //FUNCTION FOR ADD FRIEND
        jQuery('#addFriend').click(function(){
            var actionUser = jQuery('#avai-userid').attr('name');
            var actionLocation = jQuery('#actionLocation').attr('name');
            var friendStatus = "SENT";
            var data = "actionUser=" + actionUser+"&actionLocation=" + actionLocation+ "&friendStatus="+friendStatus;

            addFriend(data);
        });

        function addFriend(alldata)
        {
            jQuery.ajax({
                type: "POST",
                url: "<?php echo $this->url('success', array('action' => 'addfriend')); ?>",
                data: alldata,
                async:false,
                success: function(data) {
//                    alert(data);
                    data = JSON.parse(data);
                    var success = data['success'];
                    if(success == "1")
                    {
                        alert("Yêu cầu kết bạn đã được gửi đi. Bạn hãy chờ xác nhận!");
                    }
                    else
                    {
                        alert('Bạn đã gửi yêu cầu kết bạn, hãy chờ xác nhận từ người này');
                    }
                },
                error: function() {
                    alert("Hệ thống đang bảo trì, xin hãy thử lại sau một ít phút nữa!");
                }
            });
            return false;
        }

        jQuery('#unFriend').click(function(){
            var actionUser = jQuery('#avai-userid').attr('name');
            var actionLocation = jQuery('#actionLocation').attr('name');
            var friendStatus = "ACCEPTED";
            var data = "actionUser=" + actionUser+"&actionLocation=" + actionLocation+ "&friendStatus="+friendStatus;

            jQuery.ajax({
                type: "POST",
                url: "<?php echo $this->url('success', array('action' => 'unfriend')); ?>",
                data: data,
                async:false,
                success: function(data) {
//                    alert(data);
                    data = JSON.parse(data);
                    var success = data['success'];
                    if(success == "1")
                    {
                        alert("Hủy kết bạn thành công");
                    }
                    else
                    {
                        alert('Bạn đã gửi yêu cầu hủy kết bạn.');
                    }
                },
                error: function() {
                    alert("Hệ thống đang bảo trì, xin hãy thử lại sau một ít phút nữa!");
                }
            });
            return false;
        });


        //FUNCTION FOR SEARCH

        function instanceShowSearchResult(fullName, pathAva, userID, friendStatus)
        {
            var divsearchUser = document.createElement('div');
            divsearchUser.className = "searchUser";

            var divimagesearchUser = document.createElement('div');
            divimagesearchUser.className = "image-searchUser";
                var imgsearchUser = document.createElement('img');
                jQuery(imgsearchUser).attr('src', '<?php echo $this->basePath().'/uploads/'; ?>' + pathAva);

            var divcontentsearchUser = document.createElement('div');
            divcontentsearchUser.className = "content-searchUser";

                var tagaOfNameSearchUser = document.createElement('a');
                jQuery(tagaOfNameSearchUser).attr('href', '<?php echo $this->basePath().'/success?user=';?>' +userID);
                    var tagSpanOfNameUser = document.createElement('span');
                    tagSpanOfNameUser.className = "name-searchUser";
                    jQuery(tagSpanOfNameUser).text(fullName);

                var tagaOfBanChungUser = document.createElement('a');
                jQuery(tagaOfBanChungUser).attr('href', '#');
                    var tagSpanOfBanChungUser = document.createElement('span');
                    tagSpanOfBanChungUser.className = "banchung-searchUser";
                    jQuery(tagSpanOfBanChungUser).text("4 bạn chung");

                var tagaOfKetBan = document.createElement('a');
                jQuery(tagaOfKetBan).attr('name', userID);

                    var tagSpanOfKetBan = document.createElement('span');
                    tagSpanOfKetBan.className = "";

                    var friendCheckStatus = "Kết bạn";
                    var nameClassStatus = "btnKetban-copy";
                    if(friendStatus == "ME"){
                        friendCheckStatus = "Chính bản thân";
                    }else{
                        if(friendStatus == "SENT") {
                            friendCheckStatus ="Đã gửi yêu cầu kết bạn";

                        }
                        else{
                            if(friendStatus == "ACCEPTED") friendCheckStatus ="Đã kết bạn";
                            else
                                nameClassStatus = "btnKetban-searchUser";
                        }
                    }
                    tagaOfKetBan.className = nameClassStatus;
                    jQuery(tagSpanOfKetBan).text(friendCheckStatus);


            divsearchUser.appendChild(divimagesearchUser);
                divimagesearchUser.appendChild(imgsearchUser);
            divsearchUser.appendChild(divcontentsearchUser);
                divcontentsearchUser.appendChild(tagaOfNameSearchUser);
                    tagaOfNameSearchUser.appendChild(tagSpanOfNameUser);
                divcontentsearchUser.appendChild(tagaOfBanChungUser);
                    tagaOfBanChungUser.appendChild(tagSpanOfBanChungUser);
                divcontentsearchUser.appendChild(tagaOfKetBan);
                    tagaOfKetBan.appendChild(tagSpanOfKetBan);


            jQuery('#searchResult').append(divsearchUser);

            jQuery(tagSpanOfKetBan).each(function(){
                jQuery(this).on('click',function(){
                    var actionUser = jQuery('#avai-userid').attr('name');
                    var actionLocation = jQuery(this).parent().attr('name');

                    if(actionUser == actionLocation) {
                        alert('Bạn không thể tự kết bạn với chính mình.');
                        return;
                    }

                    var friendStatus = "SENT";
                    var data = "actionUser=" + actionUser+"&actionLocation=" + actionLocation+ "&friendStatus="+friendStatus;

                    addFriend(data);
                });
            });

        }

        function searchEverything()
        {
            var searchContent = jQuery('#txtSearch').val();
            var divSearchResult = jQuery('#searchResult');
            var actionUser = jQuery('#avai-userid').attr('name');
            var data = "actionUser="+actionUser+"&searchContent="+searchContent;

            if(searchContent == "") {
                divSearchResult.hide();
                return;
            }
//            alert(data);
            jQuery.ajax({
                type: "POST",
                url: "<?php echo $this->url('success', array('action' => 'search')); ?>",
                data: data,
                async:false,
                success: function(data) {
//                    alert(data);
                    data = JSON.parse(data);
                    var success = data['success'];
                    var checkNull = false;
                    if(success == "1")
                    {
                        divSearchResult.hide().empty();
                        if(data['result'] != null){
                            for(var i = 0; i<data['result'].length; i++){
                                var info = data['result'][i];
                                var searchUserID = info['userid']
                                var friendStatus = info['friendStatus'];
                                if(searchUserID == actionUser) {
                                    friendStatus = "ME";
                                }
                                instanceShowSearchResult(info['fullName'], info['path'],searchUserID , friendStatus);
                            }
                            divSearchResult.append('<div class="searchUser" style="border-bottom:0px;"><a href="#"><span class="readmore">Xem thêm kết quả...</span></a></div>');
                        }
                        else{
                            divSearchResult.append('<div class="searchUser" style="border-bottom:0px;"><a href="#"><span class="readmore">Không có kết quả nào phù hợp!</span></a></div>');
                        }
                        divSearchResult.show();

                        jQuery('.searchUser').hover(function(){
                           jQuery(this).addClass('newBackground');
                        }, function(){
                            jQuery(this).removeClass('newBackground');
                        });

                    }
                    else
                    {
                        alert('Tìm kiếm thất bại');
                    }
                },
                error: function() {
                    alert("Hệ thống đang bảo trì, xin hãy thử lại sau một ít phút nữa!");
                }
            });
            return false;

        }




        jQuery('#txtSearch').on('keyup', function(){
            searchEverything();
        });
        jQuery('#btnSearch').click(function(){
            searchEverything();
        });




    });
</script>

