<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle($this->translate('Zess - Cài đặt fanpage'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/jQuery.alert.css')
        ->prependStylesheet($this->basePath() . '/css/fanpage-config.css')
        ->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')

    ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/hTabs/tabs.js')
        ->prependFile($this->basePath() . '/js/chart.js')
        ->prependFile($this->basePath() . '/js/jQuery.alert.js')
        ->prependFile($this->basePath() . '/js/jquery.validate.min.js')
        ->prependFile($this->basePath() . '/js/menu_tabs/menu_tabs.js')
        ->prependFile($this->basePath() . '/js/jquery.accordion.js')
        ->prependFile($this->basePath() . '/js/jquery.easing.1.3.js')
        ->prependFile($this->basePath() . '/js/jquery.tmpl.min.js')
        ->prependFile($this->basePath() . '/js/jquery.1.7.1.min.js')
        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
    ; ?>

</head>
<body>

<div class="fiend-container" style=" width: 100%;">
    <style type="text/css">
        .ca-main{font-size: 20px !important; font-weight: bold !important;}
    </style>

    <div class="friend-content" style="width: 21%;">
        <div class="logo-zess">
            <a href="<?php echo $this->basePath().'/fanpage/';?>"><img src="<?php echo $this->basePath();?>/img/zess_logo.png"></a>
        </div>
        <ul class="ca-menu">
            <li>
                <a id="menu_home" href="<?php echo $this->basePath().'/homepage/'; ?>">
                    <span class="ca-icon">F</span>
                    <div class="ca-content">
                        <h2 class="ca-main">Trang Fanpage</h2>
                        <h3 class="ca-sub">Quay về trang fanpage</h3>
                    </div>
                </a>
            </li>
            <li>
                <a id="menu_editinfo" href="<?php echo $this->url('fanpage', array('action' => 'editinfo')); ?>">
                    <span class="ca-icon">I</span>
                    <div class="ca-content">
                        <h2 class="ca-main">Sửa thông tin trang</h2>
                        <h3 class="ca-sub">Quản lí trang fanpage</h3>
                    </div>
                </a>
            </li>
            <li>
                <a id="menu_manage" href="<?php echo $this->url('fanpage', array('action' => 'manage')); ?>">
                    <span class="ca-icon">I</span>
                    <div class="ca-content">
                        <h2 class="ca-main">Thông tin quản trị</h2>
                        <h3 class="ca-sub">Quản lí quản trị viên</h3>
                    </div>
                </a>
            </li>
            <li>
                <a id="menu_activity" href="<?php echo $this->url('fanpage', array('action' => 'activity')); ?>">
                    <span class="ca-icon">M</span>
                    <div class="ca-content">
                        <h2 class="ca-main">Hoạt động</h2>
                        <h3 class="ca-sub">Xem tình hình hoạt động</h3>
                    </div>
                </a>
            </li>

        </ul>
    </div>

    <style type="text/css">
        #result_search{
            position: relative;
            height: 100px;
            background-color: #EDEBEB;
            border-radius: 5px;
            margin-top: 40px;
            color: #000000;
            border: 3px solid #333333;
        }

        .searchUser:hover{
            /*background: linear-gradient(#333, #222);*/
            background: #0688FA;
        }
        .searchUser:hover a span {
            color: white;
        }

    </style>

    <div class="rightContent-friend" style=" float: left; width: 79%;">
        <div class="search-nav" style=" height: 70px; width: 100%; margin: 0 auto;">
            <div class="webdesigntuts-workshop" style="width: 450px; margin: 0 auto;">
                <form action="" method="">
                    <input id="search_master" type="search" placeholder="Tìm kiếm mọi thứ...">
                    <button id="btn_search_master">Search</button>
                </form>
                <div id="result_search" style="display: none;">

                    <div class="searchUser">
                        <div class="image-searchUser">
                            <img src="/zend2/public/uploads/ava-temp.png">
                        </div>
                        <div class="content-searchUser">
                            <a href="/zend2/public/success?user=user1386929104">
                                <span class="name-searchUser">Nguyễn Tấn Phát</span>
                            </a>
                            <a href="#">
                                <span class="banchung-searchUser">4 bạn chung</span>
                            </a>
                            <a name="user1386929104" class="btnKetban-copy">
                                <span class="">Chính bản thân</span>
                            </a>
                        </div>
                    </div>

                </div>
            </div>
        </div>


        <!--        Bat dau in content nhu tren-->
        <?php echo $this->content; ?>
        <?php echo $this->inlineScript() ?>


    </div>

</div>


<script type="text/javascript">
    jQuery(document).ready(function(){

        //set class for body
        jQuery('body').addClass('bodyFriendPage');

        //set with for some div
        function calWidthSearchDiv()
        {
            var winWidth = jQuery(window).width();
            var winHeight = jQuery(window).height();
            var widthBlack = winWidth - 280;
            jQuery('.fiend-container').css('width', winWidth + "px");
//            jQuery('.rightContent-friend').css('width', widthBlack + "px");
        }

        //dieu chinh div truoc khi load.
        calWidthSearchDiv();

        //on window resize
        jQuery(window).resize(function(){
            calWidthSearchDiv();
        });

        //effect for each friend
        jQuery('.ec-circle').hover(function(){
            jQuery(this).children().css('color', 'white');
        },function(){
            jQuery(this).children().css('color', 'transparent');
        });

        ///////////////start ajax for search////////////////////
        var typingTimer;
        var doneTypingInterval = 1500;
        var input_search = jQuery('#search_master');

        input_search.keyup(function(){
            clearTimeout(typingTimer);
            if (input_search.val) {
                typingTimer = setTimeout(searchMaster, doneTypingInterval);
            }
        });

        function searchMaster()
        {
            var keywords = input_search.val();
            var dataval = "keywords="+keywords;

            alert(dataval);

            jQuery.ajax({
                type: "POST",
                url: "<?php echo $this->basePath().'/searchmaster'; ?>",
                data: dataval,
                async:false,
                success: function(data) {
                    alert(data);
                    data = JSON.parse(data);

                    var success = data['success'];

                    if(success == "1")
                    {
                      alert('thanh cong');
                    }
                    else
                    {
                        alert('Tìm kiếm thất bại');
                    }
                },
                error: function() {
                    alert("Hệ thống đang bảo trì, xin hãy thử lại sau một ít phút nữa!");
                }
            });
            return false;

        }

    });

</script>
</body>
</html>

