<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle($this->translate('Zess - Mạng xã hội Ẩm thực & Du lịch Việt Nam'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/lightbox.css')
        ->prependStylesheet($this->basePath() . '/css/style.css')
//        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/jquery.jscroll.js')
        ->prependFile($this->basePath() . '/js/script.cropImage_cover.private.js')
        ->prependFile($this->basePath() . '/js/script.cropImage.private.js')
        ->prependFile($this->basePath() . '/js/jquery.imgareaselect.pack.js')
        ->prependFile($this->basePath() . '/js/prototype.js')
        ->prependFile($this->basePath() . '/js/jquery.validate.min.js')
        ->prependFile($this->basePath() . '/js/jquery.accordion.js')
        ->prependFile($this->basePath() . '/js/jquery.easing.1.3.js')
//        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/jquery.validate.min.js')
        ->prependFile($this->basePath() . '/js/jquery.1.7.1.min.js')
//        ->prependFile($this->basePath() . '/js/jquery-1.6.1.min.js')
        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
    ; ?>

</head>
<body>


<div class="fiend-container" style=" width: 100%;">

    <div class="friend-content" style="">
        <div class="logo-zess">
            <a href="<?php echo $this->basePath();?>"><img src="<?php echo $this->basePath();?>/img/zess_logo.png"></a>
        </div>
        <ul class="ca-menu">
            <li>
                <a href="<?php echo $this->basePath().'/homepage/'; ?>">
                    <span class="ca-icon">F</span>
                    <div class="ca-content">
                        <h2 class="ca-main">Trang chủ</h2>
                        <h3 class="ca-sub">Mạng xã hội Zess</h3>
                    </div>
                </a>
            </li>
            <li>
                <a href="<?php echo $this->basePath().'/success/'; ?>">
                    <span class="ca-icon">Z</span>
                    <div class="ca-content">
                        <h2 class="ca-main">Trang cá nhân</h2>
                        <h3 class="ca-sub">Quay về trang cá nhân</h3>
                    </div>
                </a>
            </li>
            <li>
                <a href="#">
                    <span class="ca-icon">t</span>
                    <div class="ca-content">
                        <h2 class="ca-main">Chọc</h2>
                        <h3 class="ca-sub">Chọc ghẹo bạn bè</h3>
                    </div>
                </a>
            </li>
            <li>
                <a href="<?php echo $this->url('success', array('action' => 'friend')); ?>">
                    <span class="ca-icon">UU</span>
                    <div class="ca-content">
                        <h2 class="ca-main">Bạn bè</h2>
                        <h3 class="ca-sub">Bạn bè & lời mời kết bạn</h3>
                    </div>
                </a>
            </li>
            <li>
                <a href="#">
                    <span class="ca-icon">@</span>
                    <div class="ca-content">
                        <h2 class="ca-main">Hộp thư</h2>
                        <h3 class="ca-sub">Hộp thư cá nhân</h3>
                    </div>
                </a>
            </li>
            <li>
                <a href="<?php echo $this->url('success', array('action' => 'update-info')); ?>">
                    <span class="ca-icon">S</span>
                    <div class="ca-content">
                        <h2 class="ca-main">Cài đặt</h2>
                        <h3 class="ca-sub">Chỉnh sửa cài đặt cá nhân</h3>
                    </div>
                </a>
            </li>

            <li>
                <a href="<?php echo $this->url('success', array('action' => 'create-fanpage')); ?>">
                    <span class="ca-icon">a</span>
                    <div class="ca-content">
                        <h2 class="ca-main">Tạo fanpage</h2>
                        <h3 class="ca-sub">Tạo trang miễn phí</h3>
                    </div>
                </a>
            </li>

        </ul>
    </div>

    <div class="rightContent-friend" style=" float: left;">
        <div class="search-nav" style=" height: 70px; width: 100%; margin: 0 auto;">
            <div class="webdesigntuts-workshop" style="width: 450px; margin: 0 auto;">
                <form action="" method="">
                    <input type="search" placeholder="Tìm kiếm mọi thứ...">
                    <button>Search</button>
                </form>
            </div>
        </div>


<!--        Bat dau in content nhu tren-->
        <?php echo $this->content; ?>
        <?php echo $this->inlineScript() ?>


    </div>

</div>


<script type="text/javascript">
    jQuery('body').addClass('bodyFriendPage');
    calWidthSearchDiv();
    function calWidthSearchDiv()
    {
        var winWidth = jQuery(window).width();
        var winHeight = jQuery(window).height();
        var widthBlack = winWidth - 280;
        jQuery('.fiend-container').css('width', winWidth + "px");
        jQuery('.rightContent-friend').css('width', widthBlack + "px");
    }
    jQuery(document).ready(function(){
        //set class for body


        //set with for some div


        //dieu chinh div truoc khi load.


        //on window resize
        jQuery(window).resize(function(){
            calWidthSearchDiv();
        });

        //effect for each friend
        jQuery('.ec-circle').hover(function(){
            jQuery(this).children().css('color', 'white');
        },function(){
            jQuery(this).children().css('color', 'transparent');
        });



    });

</script>

</body>
</html>
