<?php

namespace DoctrineMongoODMModule\Hydrator;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class ApplicationDocumentAlbumHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = $value instanceof \MongoId ? (string) $value : $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['albumid'])) {
            $value = $data['albumid'];
            $return = (string) $value;
            $this->class->reflFields['albumid']->setValue($document, $return);
            $hydratedData['albumid'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['albumdescription'])) {
            $value = $data['albumdescription'];
            $return = (string) $value;
            $this->class->reflFields['albumdescription']->setValue($document, $return);
            $hydratedData['albumdescription'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['albumname'])) {
            $value = $data['albumname'];
            $return = (string) $value;
            $this->class->reflFields['albumname']->setValue($document, $return);
            $hydratedData['albumname'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['userid'])) {
            $value = $data['userid'];
            $return = (string) $value;
            $this->class->reflFields['userid']->setValue($document, $return);
            $hydratedData['userid'] = $return;
        }
        return $hydratedData;
    }
}