<?php

namespace DoctrineMongoODMModule\Hydrator;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class ApplicationDocumentCommentHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = $value instanceof \MongoId ? (string) $value : $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['commentid'])) {
            $value = $data['commentid'];
            $return = (string) $value;
            $this->class->reflFields['commentid']->setValue($document, $return);
            $hydratedData['commentid'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['actionid'])) {
            $value = $data['actionid'];
            $return = (string) $value;
            $this->class->reflFields['actionid']->setValue($document, $return);
            $hydratedData['actionid'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['commentcontent'])) {
            $value = $data['commentcontent'];
            $return = (string) $value;
            $this->class->reflFields['commentcontent']->setValue($document, $return);
            $hydratedData['commentcontent'] = $return;
        }
        return $hydratedData;
    }
}