<?php

namespace DoctrineMongoODMModule\Hydrator;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class ApplicationDocumentImageHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = $value instanceof \MongoId ? (string) $value : $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['imageid'])) {
            $value = $data['imageid'];
            $return = (string) $value;
            $this->class->reflFields['imageid']->setValue($document, $return);
            $hydratedData['imageid'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['albumid'])) {
            $value = $data['albumid'];
            $return = (string) $value;
            $this->class->reflFields['albumid']->setValue($document, $return);
            $hydratedData['albumid'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['imagedescription'])) {
            $value = $data['imagedescription'];
            $return = (string) $value;
            $this->class->reflFields['imagedescription']->setValue($document, $return);
            $hydratedData['imagedescription'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['imagestatus'])) {
            $value = $data['imagestatus'];
            $return = (string) $value;
            $this->class->reflFields['imagestatus']->setValue($document, $return);
            $hydratedData['imagestatus'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['imagetype'])) {
            $value = $data['imagetype'];
            $return = (string) $value;
            $this->class->reflFields['imagetype']->setValue($document, $return);
            $hydratedData['imagetype'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['imagelongtitude'])) {
            $value = $data['imagelongtitude'];
            $return = (string) $value;
            $this->class->reflFields['imagelongtitude']->setValue($document, $return);
            $hydratedData['imagelongtitude'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['imagelatitude'])) {
            $value = $data['imagelatitude'];
            $return = (string) $value;
            $this->class->reflFields['imagelatitude']->setValue($document, $return);
            $hydratedData['imagelatitude'] = $return;
        }
        return $hydratedData;
    }
}