<?php

namespace DoctrineMongoODMModule\Hydrator;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class ApplicationDocumentVideoHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = $value instanceof \MongoId ? (string) $value : $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['videoid'])) {
            $value = $data['videoid'];
            $return = (string) $value;
            $this->class->reflFields['videoid']->setValue($document, $return);
            $hydratedData['videoid'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['albumid'])) {
            $value = $data['albumid'];
            $return = (string) $value;
            $this->class->reflFields['albumid']->setValue($document, $return);
            $hydratedData['albumid'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['videodescription'])) {
            $value = $data['videodescription'];
            $return = (string) $value;
            $this->class->reflFields['videodescription']->setValue($document, $return);
            $hydratedData['videodescription'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['videotype'])) {
            $value = $data['videotype'];
            $return = (string) $value;
            $this->class->reflFields['videotype']->setValue($document, $return);
            $hydratedData['videotype'] = $return;
        }
        return $hydratedData;
    }
}