<?php

namespace DoctrineMongoODMModule\Hydrator;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class ApplicationDocumentPlaceHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = $value instanceof \MongoId ? (string) $value : $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['imageid'])) {
            $value = $data['imageid'];
            $return = (string) $value;
            $this->class->reflFields['imageid']->setValue($document, $return);
            $hydratedData['imageid'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['placeid'])) {
            $value = $data['placeid'];
            $return = (string) $value;
            $this->class->reflFields['placeid']->setValue($document, $return);
            $hydratedData['placeid'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['placename'])) {
            $value = $data['placename'];
            $return = (string) $value;
            $this->class->reflFields['placename']->setValue($document, $return);
            $hydratedData['placename'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['placedescription'])) {
            $value = $data['placedescription'];
            $return = (string) $value;
            $this->class->reflFields['placedescription']->setValue($document, $return);
            $hydratedData['placedescription'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['placeaddress'])) {
            $value = $data['placeaddress'];
            $return = (string) $value;
            $this->class->reflFields['placeaddress']->setValue($document, $return);
            $hydratedData['placeaddress'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['hashtag'])) {
            $value = $data['hashtag'];
            $return = (string) $value;
            $this->class->reflFields['hashtag']->setValue($document, $return);
            $hydratedData['hashtag'] = $return;
        }
        return $hydratedData;
    }
}