<?php

namespace DoctrineMongoODMModule\Hydrator;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class ApplicationDocumentFriendHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = $value instanceof \MongoId ? (string) $value : $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['friendusersend'])) {
            $value = $data['friendusersend'];
            $return = (string) $value;
            $this->class->reflFields['friendusersend']->setValue($document, $return);
            $hydratedData['friendusersend'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['frienduserrecieve'])) {
            $value = $data['frienduserrecieve'];
            $return = (string) $value;
            $this->class->reflFields['frienduserrecieve']->setValue($document, $return);
            $hydratedData['frienduserrecieve'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['friendstatus'])) {
            $value = $data['friendstatus'];
            $return = (string) $value;
            $this->class->reflFields['friendstatus']->setValue($document, $return);
            $hydratedData['friendstatus'] = $return;
        }
        return $hydratedData;
    }
}