Trang Đăng nhập tài khoản.



<?php

if(isset($error))
    echo $error;

$form = $this->form;
$form->setAttribute('action', $this->url('login', array('action' => 'login')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('username'));
echo $this->formRow($form->get('password'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();

?>